import { ChevronLeft, Sparkles, Lock } from "lucide-react";
import { Link } from "wouter";

interface FeatureCard {
  emoji: string;
  title: string;
  description: string;
  color: string;
  bg: string;
  border: string;
  status: "soon" | "beta";
}

const COMING_SOON: FeatureCard[] = [
  { emoji: "🌎", title: "Prayer Times World Map",   description: "Visualize prayer times and Islamic centers worldwide on an interactive map.", color: "text-sky-300",    bg: "rgba(56,189,248,0.08)",    border: "rgba(56,189,248,0.2)"   },
  { emoji: "🤲", title: "AI Personalized Duas",      description: "Get duas tailored to your situation — generated by Islamic AI with Quran & Sunnah sources.", color: "text-purple-300", bg: "rgba(168,85,247,0.08)",    border: "rgba(168,85,247,0.2)"   },
  { emoji: "📖", title: "Word-by-Word Learning",     description: "Tap any Arabic word to see its meaning, root, and grammar — perfect for learning Quranic Arabic.", color: "text-emerald-300",bg: "rgba(52,211,153,0.08)",    border: "rgba(52,211,153,0.2)"   },
  { emoji: "🎤", title: "Repeat-After-Reciter",      description: "Listen to each ayah, pause, repeat aloud, and record your recitation for self-review.", color: "text-teal-300",   bg: "rgba(45,212,191,0.08)",    border: "rgba(45,212,191,0.2)"   },
  { emoji: "🕌", title: "Nearby Halal Places",       description: "Find halal restaurants, mosques, and Islamic centers near your current location.", color: "text-amber-300",  bg: "rgba(217,119,6,0.08)",     border: "rgba(217,119,6,0.2)"    },
  { emoji: "🏆", title: "Quran Reading Leaderboard", description: "See how you rank with friends and family in monthly Quran reading challenges.", color: "text-yellow-300", bg: "rgba(234,179,8,0.08)",     border: "rgba(234,179,8,0.2)"    },
  { emoji: "👥", title: "Family Reading Groups",     description: "Create a private group and read Quran together with your family — track everyone's progress.", color: "text-pink-300",   bg: "rgba(236,72,153,0.08)",    border: "rgba(236,72,153,0.2)"   },
  { emoji: "📸", title: "Scan Arabic Text",           description: "Point your camera at any Arabic text to detect Quran verses and get instant translation.", color: "text-orange-300", bg: "rgba(249,115,22,0.08)",    border: "rgba(249,115,22,0.2)"   },
  { emoji: "🧠", title: "Tajweed AI Highlighting",   description: "AI-powered color-coded Tajweed rules — ghunna, madd, qalqalah and more highlighted live.", color: "text-violet-300", bg: "rgba(139,92,246,0.08)",    border: "rgba(139,92,246,0.2)"   },
  { emoji: "🌙", title: "Auto Night Recitation",     description: "Schedule automatic Quran recitation to play softly at night while you sleep.", color: "text-indigo-300", bg: "rgba(99,102,241,0.08)",    border: "rgba(99,102,241,0.2)"   },
  { emoji: "🎨", title: "Custom Islamic Themes",     description: "Choose from 20+ custom themes — Desert Gold, Midnight Madinah, Emerald Forest, and more.", color: "text-lime-300",   bg: "rgba(132,204,22,0.08)",    border: "rgba(132,204,22,0.2)"   },
  { emoji: "📴", title: "Offline Islamic Pack",      description: "Download the complete Quran, 500+ duas, hadith, prayer guides — usable with zero internet.", color: "text-cyan-300",   bg: "rgba(34,211,238,0.08)",    border: "rgba(34,211,238,0.2)"   },
  { emoji: "🧠", title: "AI Tafsir Simplifier",      description: "Paste any verse and get a simple, modern explanation of its meaning based on classical tafsir.", color: "text-blue-300",   bg: "rgba(96,165,250,0.08)",    border: "rgba(96,165,250,0.2)"   },
  { emoji: "🎬", title: "Islamic Shorts",             description: "Short 60-second Islamic educational clips — stories, rulings, duas, and reminders.", color: "text-rose-300",   bg: "rgba(244,63,94,0.08)",     border: "rgba(244,63,94,0.2)"    },
  { emoji: "🕰️", title: "Smart Azan Alarms",         description: "Gentle Azan fade-in alarms that gradually increase in volume to wake you peacefully for Fajr.", color: "text-sky-300",    bg: "rgba(56,189,248,0.08)",    border: "rgba(56,189,248,0.2)"   },
  { emoji: "📿", title: "Animated Tasbeeh Themes",   description: "Beautiful animated bead themes for your Tasbeeh counter — gold, crystal, wooden, and more.", color: "text-amber-300",  bg: "rgba(217,119,6,0.08)",     border: "rgba(217,119,6,0.2)"    },
];

export function Discover() {
  return (
    <div
      className="min-h-screen pb-28 md:pb-10 animate-in fade-in duration-500"
      style={{ background: "linear-gradient(150deg, #071a0e 0%, #0a1f12 50%, #061610 100%)" }}
    >
      {/* Header */}
      <div className="px-5 pt-6 pb-2">
        <div className="flex items-center gap-3 mb-5">
          <Link href="/more" className="text-emerald-600 hover:text-emerald-400 transition-colors">
            <ChevronLeft className="w-6 h-6" />
          </Link>
          <div className="flex-1">
            <h1 className="text-2xl font-serif font-bold text-emerald-300">Discover Features</h1>
            <p className="text-emerald-700 text-xs mt-0.5">Coming soon to Noor Quran</p>
          </div>
          <Sparkles className="w-6 h-6 text-amber-400" />
        </div>

        {/* Hero banner */}
        <div className="rounded-3xl overflow-hidden border border-emerald-700/40 mb-5"
          style={{ background: "linear-gradient(135deg, rgba(26,92,56,0.5) 0%, rgba(13,43,26,0.6) 100%)" }}>
          <div className="h-1 w-full" style={{ background: "linear-gradient(90deg, #1a5c38, #34d399, #fbbf24, #34d399, #1a5c38)" }} />
          <div className="px-5 py-5 space-y-2">
            <div className="flex items-center gap-2">
              <span className="text-2xl">🚀</span>
              <p className="text-white font-bold text-base">Big features are coming!</p>
            </div>
            <p className="text-emerald-500 text-sm leading-relaxed">
              Our team is building AI-powered tools, community features, interactive learning, and much more. Vote for your favourites by rating the app on Play Store.
            </p>
            <a href="https://play.google.com/store/apps/details?id=com.sj64noorquran&reviewId=0"
              target="_blank" rel="noopener noreferrer"
              className="inline-flex items-center gap-2 mt-2 px-4 py-2 rounded-xl text-sm font-semibold text-white transition-all active:scale-95"
              style={{ background: "linear-gradient(135deg, #1a5c38, #16a34a)" }}>
              ⭐ Rate & Vote on Play Store
            </a>
          </div>
        </div>
      </div>

      {/* Feature grid */}
      <div className="px-4 space-y-3">
        <div className="flex items-center gap-2 mb-2">
          <Lock className="w-3.5 h-3.5 text-emerald-800" />
          <p className="text-emerald-800 text-xs font-semibold uppercase tracking-wider">In Development</p>
        </div>

        {COMING_SOON.map((f, i) => (
          <div
            key={i}
            className="flex items-center gap-4 p-4 rounded-2xl border"
            style={{ background: f.bg, borderColor: f.border }}
          >
            <div className="w-12 h-12 rounded-xl flex items-center justify-center text-2xl shrink-0"
              style={{ background: f.bg.replace("0.08", "0.15"), border: `1px solid ${f.border}` }}>
              {f.emoji}
            </div>
            <div className="flex-1 min-w-0">
              <div className="flex items-center gap-2 flex-wrap">
                <p className={`font-bold text-sm ${f.color}`}>{f.title}</p>
                <span className="text-[10px] font-bold px-1.5 py-0.5 rounded-full border border-emerald-900/40 text-emerald-800">
                  SOON
                </span>
              </div>
              <p className="text-emerald-700 text-xs mt-0.5 leading-relaxed">{f.description}</p>
            </div>
          </div>
        ))}
      </div>

      <div className="text-center mt-8 mb-4 px-6">
        <p className="text-emerald-800 text-xs leading-relaxed">
          JazakAllah Khair for your patience. We are building these features with care and quality.
          Your support helps us continue. 🤍
        </p>
      </div>
    </div>
  );
}
