/**
 * Curated practice content for the separate Arabic Reading Basics course.
 *
 * Each tuple is [fully-vowelled Arabic, learner-friendly transliteration].
 * These are deliberately real letters, syllables, words, and short Quranic
 * phrases rather than generated filler. The course generator adds the
 * listen/repeat explanation and three-choice quick check for each item.
 */

export type BeginnerPracticeSeed = readonly [arabic: string, transliteration: string];

export const BEGINNER_LEVEL_TARGET = 44;

export const BEGINNER_PRACTICE_CONTENT: Record<number, ReadonlyArray<BeginnerPracticeSeed>> = {
  // Level 2 retains the original four grouped shape lessons and adds
  // individual initial, medial, final, and isolated forms for practice.
  2: [
    ["بـ", "ba initial"],
    ["ـبـ", "ba medial"],
    ["ـب", "ba final"],
    ["ب", "ba isolated"],
    ["تـ", "ta initial"],
    ["ـتـ", "ta medial"],
    ["ـت", "ta final"],
    ["ت", "ta isolated"],
    ["ثـ", "tha initial"],
    ["ـثـ", "tha medial"],
    ["ـث", "tha final"],
    ["ث", "tha isolated"],
    ["جـ", "jeem initial"],
    ["ـجـ", "jeem medial"],
    ["ـج", "jeem final"],
    ["ج", "jeem isolated"],
    ["حـ", "ha initial"],
    ["ـحـ", "ha medial"],
    ["ـح", "ha final"],
    ["ح", "ha isolated"],
    ["سـ", "seen initial"],
    ["ـسـ", "seen medial"],
    ["ـس", "seen final"],
    ["س", "seen isolated"],
    ["شـ", "sheen initial"],
    ["ـشـ", "sheen medial"],
    ["ـش", "sheen final"],
    ["ش", "sheen isolated"],
    ["عـ", "ayn initial"],
    ["ـعـ", "ayn medial"],
    ["ـع", "ayn final"],
    ["ع", "ayn isolated"],
    ["مـ", "meem initial"],
    ["ـمـ", "meem medial"],
    ["ـم", "meem final"],
    ["م", "meem isolated"],
    ["لـ", "lam initial"],
    ["ـلـ", "lam medial"],
    ["ـل", "lam final"],
    ["ل", "lam isolated"],
  ],

  // Level 3 — Zabar / Fatha. The first 26 items isolate the short a sound;
  // the remaining words keep the learner reading common fatha-heavy forms.
  3: [
    ["تَ", "ta"],
    ["ثَ", "tha"],
    ["جَ", "ja"],
    ["حَ", "ha"],
    ["خَ", "kha"],
    ["دَ", "da"],
    ["ذَ", "dha"],
    ["رَ", "ra"],
    ["زَ", "za"],
    ["سَ", "sa"],
    ["شَ", "sha"],
    ["صَ", "saad"],
    ["ضَ", "daad"],
    ["طَ", "ta"],
    ["ظَ", "dha"],
    ["عَ", "a"],
    ["غَ", "gha"],
    ["فَ", "fa"],
    ["قَ", "qa"],
    ["كَ", "ka"],
    ["لَ", "la"],
    ["مَ", "ma"],
    ["نَ", "na"],
    ["هَ", "ha"],
    ["وَ", "wa"],
    ["يَ", "ya"],
    ["كَتَبَ", "kataba"],
    ["ذَهَبَ", "dhahaba"],
    ["جَلَسَ", "jalasa"],
    ["خَرَجَ", "kharaja"],
    ["دَخَلَ", "dakhala"],
    ["رَجَعَ", "rajaa"],
    ["فَتَحَ", "fataha"],
    ["سَجَدَ", "sajada"],
    ["شَرَبَ", "sharaba"],
    ["ضَرَبَ", "daraba"],
    ["طَلَبَ", "talaba"],
    ["عَبَدَ", "abada"],
    ["غَسَلَ", "ghasala"],
    ["قَرَأَ", "qara'a"],
    ["مَنَعَ", "mana'a"],
    ["جَمَعَ", "jama'a"],
    ["حَمَلَ", "hamala"],
  ],

  // Level 4 — Zer / Kasra. It begins with recognition of the short i sound
  // and then moves into familiar words containing a clear kasra.
  4: [
    ["تِ", "ti"],
    ["ثِ", "thi"],
    ["جِ", "ji"],
    ["حِ", "hi"],
    ["خِ", "khi"],
    ["دِ", "di"],
    ["ذِ", "dhi"],
    ["رِ", "ri"],
    ["زِ", "zi"],
    ["سِ", "si"],
    ["شِ", "shi"],
    ["صِ", "siad"],
    ["ضِ", "diad"],
    ["طِ", "ti"],
    ["ظِ", "dhi"],
    ["عِ", "i"],
    ["غِ", "ghi"],
    ["فِ", "fi"],
    ["قِ", "qi"],
    ["كِ", "ki"],
    ["لِ", "li"],
    ["مِ", "mi"],
    ["نِ", "ni"],
    ["هِ", "hi"],
    ["وِ", "wi"],
    ["يِ", "yi"],
    ["بِسْمِ", "bismi"],
    ["كِتَاب", "kitaab"],
    ["كِبَر", "kibar"],
    ["جِسْم", "jism"],
    ["حِبْر", "hibr"],
    ["ذِكْر", "dhikr"],
    ["رِجْل", "rijl"],
    ["شِتَاء", "shitaa"],
    ["صِدْق", "sidq"],
    ["طِفْل", "tifl"],
    ["عِلْم", "ilm"],
    ["فِكْر", "fikr"],
    ["قِرَاءَة", "qiraa'a"],
    ["لِسَان", "lisaan"],
    ["مِثْل", "mithl"],
    ["هِجْرَة", "hijra"],
    ["مِيزَان", "miizaan"],
  ],

  // Level 5 — Pesh / Damma. The short u sound comes first, followed by
  // common words where damma is easy to hear.
  5: [
    ["تُ", "tu"],
    ["ثُ", "thu"],
    ["جُ", "ju"],
    ["حُ", "hu"],
    ["خُ", "khu"],
    ["دُ", "du"],
    ["ذُ", "dhu"],
    ["رُ", "ru"],
    ["زُ", "zu"],
    ["سُ", "su"],
    ["شُ", "shu"],
    ["صُ", "suad"],
    ["ضُ", "duad"],
    ["طُ", "tu"],
    ["ظُ", "dhu"],
    ["عُ", "u"],
    ["غُ", "ghu"],
    ["فُ", "fu"],
    ["قُ", "qu"],
    ["كُ", "ku"],
    ["لُ", "lu"],
    ["مُ", "mu"],
    ["نُ", "nu"],
    ["هُ", "hu"],
    ["وُ", "wu"],
    ["يُ", "yu"],
    ["مُنْ", "mun"],
    ["قُلْ", "qul"],
    ["كُتُب", "kutub"],
    ["رُسُل", "rusul"],
    ["دُخُول", "dukhuul"],
    ["خُرُوج", "khuruuj"],
    ["نُور", "nuur"],
    ["سُورَة", "suura"],
    ["عُبُودَة", "ubuuda"],
    ["فُرْقَان", "furqaan"],
    ["غُرْفَة", "ghurfa"],
    ["طُفُولَة", "tufuula"],
    ["صُدُور", "suduur"],
    ["حُبُوب", "hubuub"],
    ["وُجُوه", "wujuuh"],
    ["دُرُوس", "duruus"],
  ],

  // Level 6 — Madd / long vowels. These examples deliberately cover Alif,
  // Waw, and Ya so the learner hears the two-count stretch in each form.
  6: [
    ["بَاب", "baab"],
    ["دَار", "daar"],
    ["نَار", "naar"],
    ["سَلَام", "salaam"],
    ["كِتَاب", "kitaab"],
    ["حِسَاب", "hisaab"],
    ["قَالَ", "qaala"],
    ["قَامَ", "qaama"],
    ["صَلَاة", "salaah"],
    ["زَكَاة", "zakaah"],
    ["مَال", "maal"],
    ["حَال", "haal"],
    ["مَاء", "maa'"],
    ["جَاءَ", "jaa'a"],
    ["شَاءَ", "shaa'a"],
    ["نُور", "nuur"],
    ["رَسُول", "rasuul"],
    ["يَقُول", "yaquul"],
    ["تُوبُوا", "tuubuu"],
    ["سُورَة", "suura"],
    ["قُلُوب", "quluub"],
    ["دُعَاء", "duaa'"],
    ["وُجُوه", "wujuuh"],
    ["خُشُوع", "khushuu"],
    ["فِي", "fii"],
    ["فِيل", "fiil"],
    ["كَبِير", "kabiir"],
    ["صَغِير", "saghiir"],
    ["كَرِيم", "kariim"],
    ["عَلِيم", "aliim"],
    ["حَكِيم", "hakiim"],
    ["رَحِيم", "rahiim"],
    ["دِين", "diin"],
    ["يَقِين", "yaqiin"],
    ["سَبِيل", "sabiil"],
    ["قَدِير", "qadiir"],
    ["مُسْلِمِين", "muslimiin"],
    ["أَمِين", "amiin"],
    ["يَمِين", "yamiin"],
    ["مَكِين", "makiin"],
    ["مَجِيد", "majiid"],
  ],

  // Level 7 — Tanween. Each ending is represented repeatedly in real,
  // beginner-friendly nouns and Quranic vocabulary.
  7: [
    ["قَلَمٌ", "qalamun"],
    ["بَيْتٌ", "baytun"],
    ["نُورٌ", "nuurun"],
    ["رَسُولٌ", "rasuulun"],
    ["رَجُلٌ", "rajulun"],
    ["وَلَدٌ", "waladun"],
    ["قَلْبٌ", "qalbun"],
    ["عِلْمٌ", "ilmun"],
    ["حَقٌّ", "haqqun"],
    ["طَرِيقٌ", "tariiqun"],
    ["كَبِيرٌ", "kabiirun"],
    ["غَفُورٌ", "ghafuurun"],
    ["رَحِيمٌ", "rahiimun"],
    ["كِتَابًا", "kitaaban"],
    ["قَلَمًا", "qalaman"],
    ["بَيْتًا", "baytan"],
    ["نُورًا", "nuuran"],
    ["رَسُولًا", "rasuulan"],
    ["رَجُلًا", "rajulan"],
    ["وَلَدًا", "waladan"],
    ["قَلْبًا", "qalban"],
    ["عِلْمًا", "ilman"],
    ["طَرِيقًا", "tariiqan"],
    ["كَبِيرًا", "kabiiran"],
    ["غَفُورًا", "ghafuuran"],
    ["رَحِيمًا", "rahiiman"],
    ["قَلَمٍ", "qalamin"],
    ["بَيْتٍ", "baytin"],
    ["نُورٍ", "nuurin"],
    ["رَسُولٍ", "rasuulin"],
    ["رَجُلٍ", "rajulin"],
    ["وَلَدٍ", "waladin"],
    ["قَلْبٍ", "qalbin"],
    ["عِلْمٍ", "ilmin"],
    ["طَرِيقٍ", "tariiqin"],
    ["كَبِيرٍ", "kabiirin"],
    ["غَفُورٍ", "ghafuurin"],
    ["رَحِيمٍ", "rahiimin"],
    ["صَبْرٌ", "sabrun"],
    ["شُكْرًا", "shukran"],
    ["ذِكْرٍ", "dhikrin"],
  ],

  // Level 8 — Sukoon. These move from a stopped final consonant into
  // consonant clusters found in familiar words and commands.
  8: [
    ["أَبْ", "ab"],
    ["أَخْ", "akh"],
    ["أَمْ", "am"],
    ["مِنْ", "min"],
    ["عَنْ", "an"],
    ["هَلْ", "hal"],
    ["بَلْ", "bal"],
    ["قُلْ", "qul"],
    ["خَلْق", "khalq"],
    ["شَمْس", "shams"],
    ["نَفْس", "nafs"],
    ["دَرْس", "dars"],
    ["فَجْر", "fajr"],
    ["بَحْر", "bahr"],
    ["نَهْر", "nahr"],
    ["ذِكْر", "dhikr"],
    ["شُكْر", "shukr"],
    ["صَبْر", "sabr"],
    ["أَمْر", "amr"],
    ["قَلْب", "qalb"],
    ["حَمْد", "hamd"],
    ["عَبْد", "abd"],
    ["وَقْت", "waqt"],
    ["بِنْت", "bint"],
    ["أَنْتَ", "anta"],
    ["يَكْتُبُ", "yaktubu"],
    ["يَذْهَبُ", "yadhhabu"],
    ["يَجْلِسُ", "yajlisu"],
    ["يَدْخُلُ", "yadkhulu"],
    ["يَخْرُجُ", "yakhruju"],
    ["تَسْمَعُ", "tasmau"],
    ["نَسْمَعُ", "nasmau"],
    ["اِسْم", "ism"],
    ["اُدْخُلْ", "udkhul"],
    ["اِقْرَأْ", "iqra'"],
    ["اِسْمَعْ", "isma"],
    ["فَاسْتَمِعْ", "fastami"],
    ["مُسْلِم", "muslim"],
    ["مَسْجِد", "masjid"],
    ["مَكْتَب", "maktab"],
    ["مَدْرَسَة", "madrasa"],
  ],

  // Level 9 — Shaddah. The examples begin with one doubled letter and then
  // use familiar words where the learner can feel the held consonant.
  9: [
    ["بَّ", "bba"],
    ["تَّ", "tta"],
    ["جَّ", "jja"],
    ["دَّ", "dda"],
    ["رَّ", "rra"],
    ["سَّ", "ssa"],
    ["مَّ", "mma"],
    ["نَّ", "nna"],
    ["يَّ", "yya"],
    ["رَبِّ", "rabbi"],
    ["إِنَّ", "inna"],
    ["أَنَّ", "anna"],
    ["ثُمَّ", "thumma"],
    ["لَمَّا", "lammaa"],
    ["مِمَّا", "mimmaa"],
    ["رَبَّنَا", "rabbanaa"],
    ["مُحَمَّد", "Muhammad"],
    ["مُدَرِّس", "mudarris"],
    ["سَيِّد", "sayyid"],
    ["أُمِّي", "ummii"],
    ["حُبُّ", "hubb"],
    ["حَقّ", "haqq"],
    ["مَرَّ", "marra"],
    ["مَرَّة", "marra"],
    ["الصَّلَاة", "as-salaah"],
    ["السَّمَاء", "as-samaa"],
    ["الشَّمْس", "ash-shams"],
    ["النَّاس", "an-naas"],
    ["الرَّحْمَن", "ar-rahmaan"],
    ["الرَّحِيم", "ar-rahiim"],
    ["اللَّه", "Allah"],
    ["إِيَّاك", "iyyaaka"],
    ["إِنَّا", "innaa"],
    ["إِنَّكَ", "innaka"],
    ["وَإِيَّاك", "wa iyyaaka"],
    ["عَلَّمَ", "allama"],
    ["زَيَّنَ", "zayyana"],
    ["سَبَّحَ", "sabbaha"],
    ["فَكِّرْ", "fakkir"],
    ["قَدِّمْ", "qaddim"],
    ["أَحَبَّ", "ahabba"],
  ],

  // Level 10 — Madd reinforcement. Learners revisit all three long-vowel
  // patterns in slightly longer words before beginning connected reading.
  10: [
    ["آمَنَ", "aamana"],
    ["آدَم", "Aadam"],
    ["آخِر", "aakhir"],
    ["إِيمَان", "iimaan"],
    ["إِسْلَام", "islaam"],
    ["إِيمَانُهُ", "iimaanuhu"],
    ["أُوتِيَ", "uut iya"],
    ["أُولَٰئِكَ", "ulaa'ika"],
    ["جَاهَدَ", "jaahada"],
    ["حَافِظ", "haafiz"],
    ["خَالِق", "khaaliq"],
    ["دَاوُد", "Daawuud"],
    ["ذَاكِر", "dhaakir"],
    ["سَامِع", "saami"],
    ["شَاكِر", "shaakir"],
    ["صَاحِب", "saahib"],
    ["ضَامِر", "daamir"],
    ["طَاهِر", "taahir"],
    ["عَابِد", "aabid"],
    ["غَافِر", "ghaafir"],
    ["فَاعِل", "faail"],
    ["قَادِر", "qaadir"],
    ["كَاتِب", "kaatib"],
    ["لَطِيف", "latiif"],
    ["مَالِك", "maalik"],
    ["نَادِر", "naadir"],
    ["هَادِي", "haadii"],
    ["وَاسِع", "waasi"],
    ["يَاسِين", "Yaasiin"],
    ["مَوْعِد", "mawid"],
    ["مَوْزُون", "mawzuun"],
    ["خَوْف", "khawf"],
    ["صَوْت", "sawt"],
    ["يَوْم", "yawm"],
    ["حَوْل", "hawl"],
    ["نَوْم", "nawm"],
    ["قَوْم", "qawm"],
    ["بَيْت", "bayt"],
    ["خَيْر", "khayr"],
    ["سَيْر", "sayr"],
    ["غَيْب", "ghayb"],
    ["عَيْن", "ayn"],
    ["دَيْن", "dayn"],
    ["زَيْت", "zayt"],
  ],

  // Level 11 — Simple Reading. These are short, fully-vowelled words and
  // expressions that let the learner blend the rules without long phrases.
  11: [
    ["هَذَا", "haadhaa"],
    ["هَذِهِ", "haadhihi"],
    ["ذَلِكَ", "dhaalika"],
    ["تِلْكَ", "tilka"],
    ["أَنَا", "anaa"],
    ["أَنْتَ", "anta"],
    ["هُوَ", "huwa"],
    ["هِيَ", "hiya"],
    ["نَحْنُ", "nahnu"],
    ["مَنْ", "man"],
    ["مَا", "maa"],
    ["مِنْ", "min"],
    ["فِي", "fii"],
    ["عَلَى", "alaa"],
    ["إِلَى", "ilaa"],
    ["مَعَ", "maa"],
    ["لَهُ", "lahu"],
    ["لَهَا", " lahaa"],
    ["بِهِ", "bihi"],
    ["بِهَا", "bihaa"],
    ["رَبِّي", "rabbii"],
    ["بَيْت", "bayt"],
    ["كِتَاب", "kitaab"],
    ["قَلَم", "qalam"],
    ["دَرْس", "dars"],
    ["بَاب", "baab"],
    ["نُور", "nuur"],
    ["مَاء", "maa'"],
    ["طَعَام", "ta-aam"],
    ["شَرَاب", "sharaab"],
    ["وَلَد", "walad"],
    ["بِنْت", "bint"],
    ["رَجُل", "rajul"],
    ["صَدِيق", "sadiiq"],
    ["مُعَلِّم", "muallim"],
    ["مَدْرَسَة", "madrasa"],
    ["مَسْجِد", "masjid"],
    ["سَلَام", "salaam"],
    ["صَبَاح", "sabaah"],
    ["مَسَاء", "masaa"],
  ],

  // Level 12 — Quranic Words. These are common words and expressions from
  // short surahs and daily Quran reading, kept fully vowelled for learners.
  12: [
    ["اللَّهُ", "Allaahu"],
    ["رَبِّ", "Rabbi"],
    ["الْحَمْدُ", "al-hamdu"],
    ["لِلَّهِ", "lillaahi"],
    ["الْعَالَمِينَ", "al-aalamiin"],
    ["الرَّحْمَٰنُ", "ar-rahmaanu"],
    ["الرَّحِيمِ", "ar-rahiimi"],
    ["مَالِكِ", "maaliki"],
    ["يَوْمِ", "yawmi"],
    ["الدِّينِ", "ad-diini"],
    ["إِيَّاكَ", "iyyaaka"],
    ["نَعْبُدُ", "na budu"],
    ["نَسْتَعِينُ", "nasta iinu"],
    ["اهْدِنَا", "ihdinaa"],
    ["الصِّرَاطَ", "as-siraata"],
    ["الْمُسْتَقِيمَ", "al-mustaqiima"],
    ["أَنْعَمْتَ", "anamta"],
    ["غَيْرِ", "ghayri"],
    ["الْمَغْضُوبِ", "al-maghduubi"],
    ["الضَّالِّينَ", "ad-daalliin"],
    ["أَحَدٌ", "ahadun"],
    ["الصَّمَدُ", "as-samadu"],
    ["يَلِدْ", "yalid"],
    ["يُولَدْ", "yuulad"],
    ["كُفُوًا", "kufuwan"],
    ["أَعُوذُ", "a uudhu"],
    ["رَبِّ الْفَلَقِ", "Rabbil-falaq"],
    ["غَاسِقٍ", "ghaasiqin"],
    ["إِذَا", "idhaa"],
    ["وَقَبَ", "waqaba"],
    ["النَّفَّاثَاتِ", "an-naffaathaati"],
    ["فِي الْعُقَدِ", "fil-uqadi"],
    ["حَاسِدٍ", "haasidin"],
    ["مِنْ شَرِّ", "min sharri"],
    ["النَّاسِ", "an-naasi"],
    ["مَلِكِ النَّاسِ", "malikin-naasi"],
    ["إِلَٰهِ النَّاسِ", "ilaahin-naasi"],
    ["الْوَسْوَاسِ", "al-waswaasi"],
    ["الْخَنَّاسِ", "al-khannaasi"],
  ],

  // Level 13 — Quran Reading. These short, authentic phrases prepare the
  // learner to join words while keeping each practice item manageable.
  13: [
    ["بِسْمِ اللَّهِ", "bismillaah"],
    ["الْحَمْدُ لِلَّهِ", "al-hamdu lillaah"],
    ["رَبِّ الْعَالَمِينَ", "rabbil-aalamiin"],
    ["الرَّحْمَٰنِ الرَّحِيمِ", "ar-rahmaanir-rahiim"],
    ["مَالِكِ يَوْمِ الدِّينِ", "maaliki yawmid-diin"],
    ["إِيَّاكَ نَعْبُدُ", "iyyaaka nabudu"],
    ["وَإِيَّاكَ نَسْتَعِينُ", "wa iyyaaka nasta iin"],
    ["اهْدِنَا الصِّرَاطَ", "ihdinas-siraat"],
    ["صِرَاطَ الَّذِينَ", "siraat alladhiin"],
    ["أَنْعَمْتَ عَلَيْهِمْ", "anamta alayhim"],
    ["غَيْرِ الْمَغْضُوبِ", "ghayril-maghduub"],
    ["وَلَا الضَّالِّينَ", "wa lad-daalliin"],
    ["قُلْ هُوَ اللَّهُ أَحَدٌ", "qul huwallaahu ahad"],
    ["اللَّهُ الصَّمَدُ", "Allaahus-samad"],
    ["لَمْ يَلِدْ", "lam yalid"],
    ["وَلَمْ يُولَدْ", "wa lam yuulad"],
    ["وَلَمْ يَكُنْ لَهُ", "wa lam yakun lahu"],
    ["كُفُوًا أَحَدٌ", "kufuwan ahad"],
    ["قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ", "qul a uudhu birabbil-falaq"],
    ["مِنْ شَرِّ مَا خَلَقَ", "min sharri maa khalaq"],
    ["وَمِنْ شَرِّ غَاسِقٍ", "wa min sharri ghaasiq"],
    ["إِذَا وَقَبَ", "idhaa waqab"],
    ["وَمِنْ شَرِّ النَّفَّاثَاتِ", "wa min sharrin-naffaathaat"],
    ["فِي الْعُقَدِ", "fil-uqad"],
    ["وَمِنْ شَرِّ حَاسِدٍ", "wa min sharri haasid"],
    ["إِذَا حَسَدَ", "idhaa hasad"],
    ["قُلْ أَعُوذُ بِرَبِّ النَّاسِ", "qul a uudhu birabbin-naas"],
    ["مَلِكِ النَّاسِ", "malikin-naas"],
    ["إِلَٰهِ النَّاسِ", "ilaahin-naas"],
    ["مِنْ شَرِّ الْوَسْوَاسِ", "min sharril-waswaas"],
    ["الْخَنَّاسِ", "al-khannaas"],
    ["الَّذِي يُوَسْوِسُ", "alladhii yuwaswis"],
    ["فِي صُدُورِ النَّاسِ", "fii suduurin-naas"],
    ["مِنَ الْجِنَّةِ", "minal-jinnah"],
    ["وَالنَّاسِ", "wan-naas"],
    ["إِنَّا أَعْطَيْنَاكَ", "innaa ataynaaka"],
    ["الْكَوْثَرَ", "al-kawthar"],
    ["فَصَلِّ لِرَبِّكَ", "fasalli lirabbik"],
    ["وَانْحَرْ", "wanhar"],
    ["إِنَّ شَانِئَكَ", "inna shaani'aka"],
    ["هُوَ الْأَبْتَرُ", "huwal-abtar"],
  ],
};