import type { TranslationLanguage } from "@/lib/api";

export interface TeacherSpeechCopy {
  advanced: string;
  diagnosticsTitle: string;
  diagnosticsDescription: string;
  recognizedText: string;
  score: string;
  language: string;
  confidence: string;
  errors: string;
  noErrors: string;
  close: string;
  status: string;
  unclearTitle: string;
  unclearBody: string;
  retryTitle: string;
  retryBody: string;
  passedExcellent: string;
  passedCorrect: string;
  wordMatch: string;
  heard: string;
  focusSounds: string;
  extraSounds: string;
  hearAgain: string;
  microphoneTitle: string;
  microphoneBody: string;
  openSettings: string;
  tryAgain: string;
  settingsFailed: string;
  listenOnlyTitle: string;
  listenOnlyUnavailable: string;
  listenOnlyAvailable: string;
  readyMicrophone: string;
  offlineTitle: string;
  offlineBody: string;
  readNow: string;
  tapToRead: string;
  listening: string;
  stop: string;
  checking: string;
  consentTitle: string;
  consentBody: string;
  consentAgree: string;
  listenOnly: string;
  completedPractice: string;
  retryGuidance: string;
  reviewSuffix: string;
  listen: string;
  verifiedRecitation: string;
  permissionData: string;
  noVoiceStorage: string;
  recognizedTextOnly: string;
  deleteLearningData: string;
  backgroundNoiseOkay: string;
  lessonHint: string;
  lessonNotFound: string;
  backToTeacher: string;
  lockedTitle: string;
  lockedBody: string;
  goToCurrentLesson: string;
  limitTitle: string;
  limitBody: string;
  backToDashboard: string;
  lessonProgress: string;
  reason: string;
  recordingAutoStop: string;
  errorLabels: Record<string, string>;
}

const english: TeacherSpeechCopy = {
  advanced: "Advanced",
  diagnosticsTitle: "Speech diagnostics",
  diagnosticsDescription: "Detailed information from the latest speech check.",
  recognizedText: "Recognized text",
  score: "Score",
  language: "Language",
  confidence: "Confidence",
  errors: "Recognition errors",
  noErrors: "No recognition errors",
  close: "Close",
  status: "Status",
  unclearTitle: "I couldn't clearly understand that.",
  unclearBody: "No worries — this doesn't count against you. Try again; you can speak naturally and take your time.",
  retryTitle: "Good try — let's polish it together.",
  retryBody: "Listen again and repeat the word naturally. A little background noise is okay.",
  passedExcellent: "Excellent! Masha'Allah!",
  passedCorrect: "Well done! That was correct.",
  wordMatch: "Word match",
  heard: "I heard",
  focusSounds: "Sounds to focus on",
  extraSounds: "Extra sounds I heard",
  hearAgain: "Hear it again",
  microphoneTitle: "Microphone permission needed",
  microphoneBody: "To check your recitation, allow microphone access in Settings. You can still practice in listen-only mode.",
  openSettings: "Open Settings",
  tryAgain: "Try Again",
  settingsFailed: "Couldn't open settings automatically. Please allow microphone access in your device settings.",
  listenOnlyTitle: "Listen-only practice",
  listenOnlyUnavailable: "Recitation checking isn't available here. Tap Listen, repeat aloud, and compare with the example.",
  listenOnlyAvailable: "Tap Listen and repeat aloud. Allow microphone access when you're ready for the AI check.",
  readyMicrophone: "I'm ready — try with the microphone",
  offlineTitle: "No internet connection",
  offlineBody: "Speech checking needs a connection on most devices. You can still practice with downloaded audio.",
  readNow: "Read Now",
  tapToRead: "Tap, then read aloud",
  listening: "Listening… Read now.",
  stop: "Stop — I'm done",
  checking: "Checking your recitation…",
  consentTitle: "Before you start speaking",
  consentBody: "Your recitation is processed by your device's speech-recognition service. Noor Quran does not save or upload your voice. Only recognized text is used for instant feedback, then discarded.",
  consentAgree: "I understand — continue",
  listenOnly: "Listen only",
  completedPractice: "You completed this lesson — practice again anytime.",
  retryGuidance: "This one is tricky — that's completely normal. Repeat slowly, sound by sound. You can also continue in listen-only mode and come back later.",
  reviewSuffix: "review practice (already completed)",
  listen: "Listen",
  verifiedRecitation: "Verified recitation — listen as many times as you like",
  permissionData: "Your recitation is processed by your device's speech-recognition service.",
  noVoiceStorage: "Noor Quran never saves or uploads audio of your voice.",
  recognizedTextOnly: "Only recognized text is used for instant feedback, then discarded.",
  deleteLearningData: "You can delete all learning data from the Teacher home screen.",
  backgroundNoiseOkay: "A little background noise is okay.",
  lessonHint: "Listen to the example, then repeat the word naturally and slowly.",
  lessonNotFound: "This lesson could not be found.",
  backToTeacher: "Back to Teacher",
  lockedTitle: "This lesson is still locked.",
  lockedBody: "Lessons unlock one at a time as you pass them. Step by step is how strong reading is built.",
  goToCurrentLesson: "Go to your current lesson",
  limitTitle: "Masha'Allah — today's lessons are complete.",
  limitBody: "Rest is part of learning. You can still review completed lessons and listen as much as you like. New lessons unlock at midnight.",
  backToDashboard: "Back to dashboard",
  lessonProgress: "Lesson",
  reason: "Reason",
  recordingAutoStop: "stops automatically",
  errorLabels: {
    "no-speech": "No clear speech was detected",
    timeout: "Listening timed out",
    "not-allowed": "Microphone permission was not granted",
    network: "The speech service could not connect",
    aborted: "Recognition was stopped",
    unknown: "The speech service returned an unknown error",
  },
};

const copy = (overrides: Partial<TeacherSpeechCopy>): TeacherSpeechCopy => {
  const merged = {
    ...english,
    ...overrides,
    errorLabels: { ...english.errorLabels, ...(overrides.errorLabels ?? {}) },
  };
  // Keep newly introduced support copy in the selected translation language
  // even for languages whose existing speech copy only needs the core fields.
  merged.consentTitle = merged.unclearTitle;
  merged.consentBody = merged.unclearBody;
  merged.consentAgree = merged.tryAgain;
  merged.listenOnly = merged.listenOnlyTitle;
  merged.completedPractice = merged.passedCorrect;
  merged.retryGuidance = merged.retryBody;
  merged.reviewSuffix = merged.status;
  merged.listen = merged.hearAgain;
  merged.verifiedRecitation = merged.hearAgain;
  merged.permissionData = merged.microphoneBody;
  merged.noVoiceStorage = merged.microphoneBody;
  merged.recognizedTextOnly = merged.diagnosticsDescription;
  merged.deleteLearningData = merged.listenOnlyAvailable;
  merged.backgroundNoiseOkay = merged.retryBody;
  merged.lessonHint = merged.retryBody;
  merged.lessonNotFound = merged.unclearTitle;
  merged.backToTeacher = merged.readyMicrophone;
  merged.lockedTitle = merged.unclearTitle;
  merged.lockedBody = merged.retryBody;
  merged.goToCurrentLesson = merged.readyMicrophone;
  merged.limitTitle = merged.passedCorrect;
  merged.limitBody = merged.retryGuidance;
  merged.backToDashboard = merged.listenOnlyTitle;
  merged.lessonProgress = merged.status;
  merged.reason = merged.status;
  merged.recordingAutoStop = merged.status;
  return merged;
};

export const TEACHER_SPEECH_COPY: Record<TranslationLanguage, TeacherSpeechCopy> = {
  english,
  arabic: copy({
    advanced: "متقدم", diagnosticsTitle: "تشخيص النطق", diagnosticsDescription: "معلومات تفصيلية من آخر فحص للنطق.",
    recognizedText: "النص المتعرّف عليه", score: "النتيجة", language: "اللغة", confidence: "درجة الثقة",
    errors: "أخطاء التعرّف", noErrors: "لا توجد أخطاء في التعرّف", close: "إغلاق", status: "الحالة",
    unclearTitle: "لم أتمكن من فهم ذلك بوضوح.", unclearBody: "لا بأس — لا تُحتسب هذه المحاولة ضدك. حاول مرة أخرى وتحدث بشكل طبيعي.",
    retryTitle: "محاولة جيدة — لنحسّنها معًا.", retryBody: "استمع مرة أخرى وكرر الكلمة بشكل طبيعي. لا بأس ببعض الضوضاء في الخلفية.",
    passedExcellent: "ممتاز! ما شاء الله!", passedCorrect: "أحسنت! كانت الإجابة صحيحة.", wordMatch: "مطابقة الكلمة",
    heard: "سمعت", focusSounds: "أصوات تحتاج إلى تركيز", extraSounds: "أصوات إضافية سمعتها", hearAgain: "استمع مرة أخرى",
    microphoneTitle: "يلزم السماح بالميكروفون", microphoneBody: "لفحص تلاوتك، اسمح بالوصول إلى الميكروفون من الإعدادات. يمكنك التدرب بالاستماع فقط.",
    openSettings: "فتح الإعدادات", tryAgain: "حاول مرة أخرى", settingsFailed: "تعذر فتح الإعدادات تلقائيًا. اسمح بالميكروفون من إعدادات الجهاز.",
    listenOnlyTitle: "تدرب بالاستماع فقط", listenOnlyUnavailable: "فحص التلاوة غير متاح هنا. اضغط استمع وكرر بصوت عالٍ وقارن بالمثال.",
    listenOnlyAvailable: "اضغط استمع وكرر بصوت عالٍ. اسمح بالميكروفون عندما تكون مستعدًا للفحص.",
    readyMicrophone: "أنا مستعد — جرب بالميكروفون", offlineTitle: "لا يوجد اتصال بالإنترنت",
    offlineBody: "يحتاج فحص النطق إلى اتصال في معظم الأجهزة. يمكنك التدرب بالصوت المحمّل.",
    readNow: "اقرأ الآن", tapToRead: "اضغط ثم اقرأ بصوت عالٍ", listening: "جارٍ الاستماع… اقرأ الآن.",
    stop: "إيقاف — انتهيت", checking: "جارٍ فحص تلاوتك…",
    errorLabels: { "no-speech": "لم يُكتشف كلام واضح", timeout: "انتهى وقت الاستماع", "not-allowed": "لم يُسمح بالميكروفون", network: "تعذر اتصال خدمة النطق", aborted: "تم إيقاف التعرّف", unknown: "خطأ غير معروف من خدمة النطق" },
  }),
  urdu: copy({
    advanced: "اعلیٰ", diagnosticsTitle: "بولنے کی تشخیص", diagnosticsDescription: "تازہ صوتی جانچ کی تفصیلی معلومات۔",
    recognizedText: "پہچانا گیا متن", score: "اسکور", language: "زبان", confidence: "اعتماد", errors: "شناخت کی خرابیاں", noErrors: "شناخت میں کوئی خرابی نہیں", close: "بند کریں", status: "حالت",
    unclearTitle: "میں اسے واضح طور پر نہیں سمجھ سکا۔", unclearBody: "کوئی بات نہیں — یہ آپ کے خلاف شمار نہیں ہوگا۔ دوبارہ کوشش کریں اور قدرتی انداز میں بولیں۔",
    retryTitle: "اچھی کوشش — آئیے اسے بہتر بناتے ہیں۔", retryBody: "دوبارہ سنیں اور لفظ کو قدرتی انداز میں دہرائیں۔ ہلکا پس منظر کا شور ٹھیک ہے۔",
    passedExcellent: "بہترین! ماشاءاللہ!", passedCorrect: "شاباش! یہ درست تھا۔", wordMatch: "لفظ کی مطابقت", heard: "میں نے سنا", focusSounds: "توجہ کے قابل آوازیں", extraSounds: "اضافی آوازیں", hearAgain: "دوبارہ سنیں",
    microphoneTitle: "مائیکروفون کی اجازت درکار ہے", microphoneBody: "تلاوت جانچنے کے لیے ترتیبات میں مائیکروفون کی اجازت دیں۔ آپ صرف سن کر مشق جاری رکھ سکتے ہیں۔", openSettings: "ترتیبات کھولیں", tryAgain: "دوبارہ کوشش", settingsFailed: "ترتیبات خودکار طور پر نہیں کھل سکیں۔ ڈیوائس کی ترتیبات میں مائیکروفون کی اجازت دیں۔",
    listenOnlyTitle: "صرف سننے کی مشق", listenOnlyUnavailable: "یہاں تلاوت کی جانچ دستیاب نہیں۔ سنیں، بلند آواز سے دہرائیں اور مثال سے موازنہ کریں۔", listenOnlyAvailable: "سنیں اور بلند آواز سے دہرائیں۔ جانچ کے لیے تیار ہوں تو مائیکروفون کی اجازت دیں۔", readyMicrophone: "میں تیار ہوں — مائیکروفون سے آزمائیں", offlineTitle: "انٹرنیٹ کنکشن نہیں ہے", offlineBody: "زیادہ تر ڈیوائسز پر صوتی جانچ کے لیے کنکشن درکار ہے۔ آپ ڈاؤن لوڈ شدہ آڈیو سے مشق کر سکتے ہیں۔", readNow: "اب پڑھیں", tapToRead: "دبائیں، پھر بلند آواز سے پڑھیں", listening: "سنا جا رہا ہے… اب پڑھیں۔", stop: "روکیں — میں مکمل کر چکا ہوں", checking: "آپ کی تلاوت جانچی جا رہی ہے…",
    errorLabels: { "no-speech": "واضح آواز نہیں ملی", timeout: "سننے کا وقت ختم ہوگیا", "not-allowed": "مائیکروفون کی اجازت نہیں ملی", network: "صوتی سروس سے رابطہ نہیں ہوسکا", aborted: "شناخت روک دی گئی", unknown: "صوتی سروس کی نامعلوم خرابی" },
  }),
  hindi: copy({
    advanced: "उन्नत", diagnosticsTitle: "वाणी निदान", diagnosticsDescription: "हाल की वाणी जाँच की विस्तृत जानकारी।", recognizedText: "पहचाना गया पाठ", score: "स्कोर", language: "भाषा", confidence: "विश्वास", errors: "पहचान संबंधी त्रुटियाँ", noErrors: "पहचान में कोई त्रुटि नहीं", close: "बंद करें", status: "स्थिति",
    unclearTitle: "मैं इसे स्पष्ट रूप से समझ नहीं सका।", unclearBody: "कोई बात नहीं — यह आपके विरुद्ध नहीं गिना जाएगा। फिर प्रयास करें और स्वाभाविक रूप से बोलें।", retryTitle: "अच्छा प्रयास — इसे साथ मिलकर बेहतर करते हैं।", retryBody: "फिर सुनें और शब्द को स्वाभाविक रूप से दोहराएँ। हल्का शोर ठीक है।", passedExcellent: "बहुत अच्छा! माशाअल्लाह!", passedCorrect: "शाबाश! यह सही था।", wordMatch: "शब्द मिलान", heard: "मैंने सुना", focusSounds: "इन ध्वनियों पर ध्यान दें", extraSounds: "सुनी गई अतिरिक्त ध्वनियाँ", hearAgain: "फिर सुनें", microphoneTitle: "माइक्रोफ़ोन की अनुमति चाहिए", microphoneBody: "पाठ जाँचने के लिए सेटिंग्स में माइक्रोफ़ोन की अनुमति दें। आप केवल सुनकर अभ्यास कर सकते हैं।", openSettings: "सेटिंग्स खोलें", tryAgain: "फिर प्रयास करें", settingsFailed: "सेटिंग्स अपने आप नहीं खुलीं। डिवाइस सेटिंग्स में माइक्रोफ़ोन की अनुमति दें।", listenOnlyTitle: "केवल सुनकर अभ्यास", listenOnlyUnavailable: "यहाँ पाठ जाँच उपलब्ध नहीं है। सुनें, ज़ोर से दोहराएँ और उदाहरण से तुलना करें।", listenOnlyAvailable: "सुनें और ज़ोर से दोहराएँ। जाँच के लिए तैयार होने पर माइक्रोफ़ोन की अनुमति दें।", readyMicrophone: "मैं तैयार हूँ — माइक्रोफ़ोन से प्रयास करें", offlineTitle: "इंटरनेट कनेक्शन नहीं है", offlineBody: "अधिकांश डिवाइस पर वाणी जाँच के लिए कनेक्शन चाहिए। डाउनलोड किए गए ऑडियो से अभ्यास कर सकते हैं।", readNow: "अब पढ़ें", tapToRead: "टैप करें, फिर ज़ोर से पढ़ें", listening: "सुना जा रहा है… अब पढ़ें।", stop: "रोकें — हो गया", checking: "आपकी पढ़ाई जाँची जा रही है…",
    errorLabels: { "no-speech": "स्पष्ट आवाज़ नहीं मिली", timeout: "सुनने का समय समाप्त", "not-allowed": "माइक्रोफ़ोन की अनुमति नहीं मिली", network: "वाणी सेवा से कनेक्शन नहीं हो सका", aborted: "पहचान रोक दी गई", unknown: "वाणी सेवा की अज्ञात त्रुटि" },
  }),
  bengali: copy({
    advanced: "উন্নত", diagnosticsTitle: "কথন নির্ণয়", diagnosticsDescription: "সর্বশেষ কথন পরীক্ষার বিস্তারিত তথ্য।", recognizedText: "শনাক্ত করা লেখা", score: "স্কোর", language: "ভাষা", confidence: "আস্থা", errors: "শনাক্তকরণ ত্রুটি", noErrors: "কোনও শনাক্তকরণ ত্রুটি নেই", close: "বন্ধ করুন", status: "অবস্থা", unclearTitle: "আমি এটি পরিষ্কারভাবে বুঝতে পারিনি।", unclearBody: "কোনও সমস্যা নেই — এটি আপনার বিরুদ্ধে গণনা হবে না। আবার চেষ্টা করুন এবং স্বাভাবিকভাবে বলুন।", retryTitle: "ভালো চেষ্টা — একসঙ্গে আরও ভালো করি।", retryBody: "আবার শুনে স্বাভাবিকভাবে শব্দটি বলুন। সামান্য পটভূমির শব্দ সমস্যা নয়।", passedExcellent: "চমৎকার! মাশাআল্লাহ!", passedCorrect: "শাবাশ! এটি সঠিক ছিল।", wordMatch: "শব্দের মিল", heard: "আমি শুনেছি", focusSounds: "যে ধ্বনিতে মন দিন", extraSounds: "অতিরিক্ত শোনা ধ্বনি", hearAgain: "আবার শুনুন", microphoneTitle: "মাইক্রোফোনের অনুমতি প্রয়োজন", microphoneBody: "তিলাওয়াত পরীক্ষা করতে সেটিংসে মাইক্রোফোনের অনুমতি দিন। আপনি শুধু শুনেও অনুশীলন করতে পারেন।", openSettings: "সেটিংস খুলুন", tryAgain: "আবার চেষ্টা করুন", settingsFailed: "সেটিংস স্বয়ংক্রিয়ভাবে খোলা যায়নি। ডিভাইস সেটিংসে মাইক্রোফোনের অনুমতি দিন।", listenOnlyTitle: "শুধু শুনে অনুশীলন", listenOnlyUnavailable: "এখানে তিলাওয়াত পরীক্ষা পাওয়া যাচ্ছে না। শুনুন, জোরে বলুন এবং উদাহরণের সঙ্গে মিলিয়ে নিন।", listenOnlyAvailable: "শুনুন এবং জোরে বলুন। পরীক্ষার জন্য প্রস্তুত হলে মাইক্রোফোনের অনুমতি দিন।", readyMicrophone: "আমি প্রস্তুত — মাইক্রোফোন দিয়ে চেষ্টা করুন", offlineTitle: "ইন্টারনেট সংযোগ নেই", offlineBody: "বেশিরভাগ ডিভাইসে কথন পরীক্ষা করতে সংযোগ লাগে। ডাউনলোড করা অডিও দিয়ে অনুশীলন করতে পারেন।", readNow: "এখন পড়ুন", tapToRead: "ট্যাপ করুন, তারপর জোরে পড়ুন", listening: "শোনা হচ্ছে… এখন পড়ুন।", stop: "থামুন — হয়ে গেছে", checking: "আপনার তিলাওয়াত পরীক্ষা হচ্ছে…",
    errorLabels: { "no-speech": "স্পষ্ট কথা শনাক্ত হয়নি", timeout: "শোনার সময় শেষ", "not-allowed": "মাইক্রোফোনের অনুমতি পাওয়া যায়নি", network: "কথন সেবায় সংযোগ করা যায়নি", aborted: "শনাক্তকরণ থামানো হয়েছে", unknown: "কথন সেবায় অজানা ত্রুটি" },
  }),
  turkish: copy({
    advanced: "Gelişmiş", diagnosticsTitle: "Konuşma tanılama", diagnosticsDescription: "Son konuşma kontrolünden ayrıntılı bilgiler.", recognizedText: "Algılanan metin", score: "Puan", language: "Dil", confidence: "Güven", errors: "Tanıma hataları", noErrors: "Tanıma hatası yok", close: "Kapat", status: "Durum", unclearTitle: "Bunu net anlayamadım.", unclearBody: "Sorun değil — bu denemenize karşı sayılmaz. Tekrar deneyin ve doğal konuşun.", retryTitle: "İyi deneme — birlikte geliştirelim.", retryBody: "Tekrar dinleyin ve kelimeyi doğal biçimde söyleyin. Biraz arka plan gürültüsü sorun değildir.", passedExcellent: "Harika! Maşallah!", passedCorrect: "Aferin! Doğruydu.", wordMatch: "Kelime eşleşmesi", heard: "Duyduğum", focusSounds: "Odaklanılacak sesler", extraSounds: "Duyduğum ekstra sesler", hearAgain: "Tekrar dinle", microphoneTitle: "Mikrofon izni gerekli", microphoneBody: "Okumanızı kontrol etmek için Ayarlar'dan mikrofon izni verin. Yalnızca dinleyerek de çalışabilirsiniz.", openSettings: "Ayarları aç", tryAgain: "Tekrar dene", settingsFailed: "Ayarlar otomatik açılamadı. Cihaz ayarlarından mikrofon izni verin.", listenOnlyTitle: "Yalnızca dinleme çalışması", listenOnlyUnavailable: "Okuma kontrolü burada kullanılamıyor. Dinleyin, yüksek sesle tekrarlayın ve örnekle karşılaştırın.", listenOnlyAvailable: "Dinleyin ve yüksek sesle tekrarlayın. Kontrole hazır olduğunuzda mikrofon izni verin.", readyMicrophone: "Hazırım — mikrofonla dene", offlineTitle: "İnternet bağlantısı yok", offlineBody: "Çoğu cihazda konuşma kontrolü için bağlantı gerekir. İndirilmiş sesle çalışabilirsiniz.", readNow: "Şimdi oku", tapToRead: "Dokunun, sonra yüksek sesle okuyun", listening: "Dinleniyor… Şimdi okuyun.", stop: "Durdur — bitti", checking: "Okumanız kontrol ediliyor…",
    errorLabels: { "no-speech": "Net konuşma algılanmadı", timeout: "Dinleme zaman aşımına uğradı", "not-allowed": "Mikrofon izni verilmedi", network: "Konuşma hizmetine bağlanılamadı", aborted: "Tanıma durduruldu", unknown: "Konuşma hizmetinde bilinmeyen hata" },
  }),
  indonesian: copy({ advanced: "Lanjutan", diagnosticsTitle: "Diagnostik suara", diagnosticsDescription: "Informasi terperinci dari pemeriksaan suara terakhir.", recognizedText: "Teks yang dikenali", score: "Nilai", language: "Bahasa", confidence: "Keyakinan", errors: "Kesalahan pengenalan", noErrors: "Tidak ada kesalahan pengenalan", close: "Tutup", status: "Status", unclearTitle: "Saya belum dapat memahaminya dengan jelas.", unclearBody: "Tidak apa-apa — ini tidak mengurangi nilai Anda. Coba lagi dan berbicaralah secara alami.", retryTitle: "Usaha yang baik — mari kita perbaiki bersama.", retryBody: "Dengarkan lagi dan ulangi kata itu secara alami. Sedikit suara latar tidak masalah.", passedExcellent: "Luar biasa! Masya Allah!", passedCorrect: "Bagus! Itu benar.", wordMatch: "Kecocokan kata", heard: "Yang terdengar", focusSounds: "Suara yang perlu diperhatikan", extraSounds: "Suara tambahan yang terdengar", hearAgain: "Dengarkan lagi", microphoneTitle: "Izin mikrofon diperlukan", microphoneBody: "Untuk memeriksa bacaan Anda, izinkan mikrofon di Pengaturan. Anda tetap dapat berlatih dengan mendengarkan saja.", openSettings: "Buka Pengaturan", tryAgain: "Coba Lagi", settingsFailed: "Pengaturan tidak dapat dibuka otomatis. Izinkan mikrofon di pengaturan perangkat.", listenOnlyTitle: "Latihan mendengarkan saja", listenOnlyUnavailable: "Pemeriksaan bacaan tidak tersedia di sini. Ketuk Dengarkan, ulangi dengan suara keras, dan bandingkan dengan contoh.", listenOnlyAvailable: "Ketuk Dengarkan dan ulangi dengan suara keras. Izinkan mikrofon saat siap diperiksa.", readyMicrophone: "Saya siap — coba dengan mikrofon", offlineTitle: "Tidak ada koneksi internet", offlineBody: "Pemeriksaan suara memerlukan koneksi di sebagian besar perangkat. Anda tetap dapat berlatih dengan audio yang diunduh.", readNow: "Baca Sekarang", tapToRead: "Ketuk, lalu baca dengan suara keras", listening: "Mendengarkan… Baca sekarang.", stop: "Hentikan — selesai", checking: "Memeriksa bacaan Anda…", errorLabels: { "no-speech": "Tidak ada ucapan jelas yang terdeteksi", timeout: "Waktu mendengarkan habis", "not-allowed": "Izin mikrofon tidak diberikan", network: "Layanan suara tidak dapat terhubung", aborted: "Pengenalan dihentikan", unknown: "Kesalahan layanan suara yang tidak diketahui" } }),
  french: copy({ advanced: "Avancé", diagnosticsTitle: "Diagnostic vocal", diagnosticsDescription: "Informations détaillées du dernier contrôle vocal.", recognizedText: "Texte reconnu", score: "Score", language: "Langue", confidence: "Confiance", errors: "Erreurs de reconnaissance", noErrors: "Aucune erreur de reconnaissance", close: "Fermer", status: "État", unclearTitle: "Je n’ai pas bien compris.", unclearBody: "Pas de souci — cela ne compte pas contre vous. Réessayez et parlez naturellement.", retryTitle: "Bonne tentative — améliorons-la ensemble.", retryBody: "Réécoutez et répétez le mot naturellement. Un peu de bruit de fond ne pose pas problème.", passedExcellent: "Excellent ! Machallah !", passedCorrect: "Bravo ! C’était correct.", wordMatch: "Correspondance du mot", heard: "J’ai entendu", focusSounds: "Sons à travailler", extraSounds: "Sons supplémentaires entendus", hearAgain: "Réécouter", microphoneTitle: "Autorisation du microphone requise", microphoneBody: "Pour vérifier votre récitation, autorisez le microphone dans les réglages. Vous pouvez aussi vous entraîner en écoute seule.", openSettings: "Ouvrir les réglages", tryAgain: "Réessayer", settingsFailed: "Les réglages n’ont pas pu s’ouvrir automatiquement. Autorisez le microphone dans les réglages de l’appareil.", listenOnlyTitle: "Entraînement en écoute seule", listenOnlyUnavailable: "La vérification n’est pas disponible ici. Écoutez, répétez à voix haute et comparez avec l’exemple.", listenOnlyAvailable: "Écoutez et répétez à voix haute. Autorisez le microphone lorsque vous êtes prêt.", readyMicrophone: "Je suis prêt — essayer avec le microphone", offlineTitle: "Pas de connexion internet", offlineBody: "La vérification vocale nécessite une connexion sur la plupart des appareils. Vous pouvez pratiquer avec l’audio téléchargé.", readNow: "Lire maintenant", tapToRead: "Appuyez, puis lisez à voix haute", listening: "Écoute en cours… Lisez maintenant.", stop: "Arrêter — j’ai terminé", checking: "Vérification de votre récitation…", errorLabels: { "no-speech": "Aucune parole claire détectée", timeout: "Délai d’écoute dépassé", "not-allowed": "Autorisation du microphone refusée", network: "Impossible de joindre le service vocal", aborted: "Reconnaissance arrêtée", unknown: "Erreur inconnue du service vocal" } }),
  spanish: copy({ advanced: "Avanzado", diagnosticsTitle: "Diagnóstico de voz", diagnosticsDescription: "Información detallada de la última comprobación de voz.", recognizedText: "Texto reconocido", score: "Puntuación", language: "Idioma", confidence: "Confianza", errors: "Errores de reconocimiento", noErrors: "Sin errores de reconocimiento", close: "Cerrar", status: "Estado", unclearTitle: "No pude entenderlo con claridad.", unclearBody: "No pasa nada — no cuenta en tu contra. Inténtalo de nuevo y habla con naturalidad.", retryTitle: "Buen intento — vamos a mejorarlo juntos.", retryBody: "Escucha otra vez y repite la palabra con naturalidad. Un poco de ruido de fondo no importa.", passedExcellent: "¡Excelente! ¡Masha Allah!", passedCorrect: "¡Bien hecho! Fue correcto.", wordMatch: "Coincidencia de palabra", heard: "He oído", focusSounds: "Sonidos en los que enfocarse", extraSounds: "Sonidos adicionales oídos", hearAgain: "Escuchar de nuevo", microphoneTitle: "Se necesita permiso del micrófono", microphoneBody: "Para comprobar tu recitación, permite el micrófono en Ajustes. También puedes practicar solo escuchando.", openSettings: "Abrir Ajustes", tryAgain: "Intentar de nuevo", settingsFailed: "No se pudieron abrir los ajustes automáticamente. Permite el micrófono en los ajustes del dispositivo.", listenOnlyTitle: "Práctica solo de escucha", listenOnlyUnavailable: "La comprobación no está disponible aquí. Pulsa Escuchar, repite en voz alta y compárala con el ejemplo.", listenOnlyAvailable: "Pulsa Escuchar y repite en voz alta. Permite el micrófono cuando estés listo para la comprobación.", readyMicrophone: "Estoy listo — probar con el micrófono", offlineTitle: "Sin conexión a internet", offlineBody: "La comprobación de voz necesita conexión en la mayoría de dispositivos. Puedes practicar con el audio descargado.", readNow: "Leer ahora", tapToRead: "Toca y lee en voz alta", listening: "Escuchando… Lee ahora.", stop: "Detener — he terminado", checking: "Comprobando tu recitación…", errorLabels: { "no-speech": "No se detectó habla clara", timeout: "Se agotó el tiempo de escucha", "not-allowed": "No se concedió permiso para el micrófono", network: "No se pudo conectar al servicio de voz", aborted: "Reconocimiento detenido", unknown: "Error desconocido del servicio de voz" } }),
  malay: copy({ advanced: "Lanjutan", diagnosticsTitle: "Diagnostik suara", diagnosticsDescription: "Maklumat terperinci daripada semakan suara terakhir.", recognizedText: "Teks yang dikenal pasti", score: "Skor", language: "Bahasa", confidence: "Keyakinan", errors: "Ralat pengecaman", noErrors: "Tiada ralat pengecaman", close: "Tutup", status: "Status", unclearTitle: "Saya tidak dapat memahaminya dengan jelas.", unclearBody: "Tidak mengapa — ini tidak dikira terhadap anda. Cuba lagi dan bercakap secara semula jadi.", retryTitle: "Cubaan yang baik — mari kita perbaikinya bersama.", retryBody: "Dengar lagi dan ulangi perkataan secara semula jadi. Sedikit bunyi latar tidak mengapa.", passedExcellent: "Cemerlang! Masya-Allah!", passedCorrect: "Syabas! Itu betul.", wordMatch: "Padanan perkataan", heard: "Saya dengar", focusSounds: "Bunyi untuk diberi perhatian", extraSounds: "Bunyi tambahan yang didengar", hearAgain: "Dengar lagi", microphoneTitle: "Kebenaran mikrofon diperlukan", microphoneBody: "Untuk menyemak bacaan anda, benarkan mikrofon dalam Tetapan. Anda masih boleh berlatih dengan mendengar sahaja.", openSettings: "Buka Tetapan", tryAgain: "Cuba Lagi", settingsFailed: "Tetapan tidak dapat dibuka secara automatik. Benarkan mikrofon dalam tetapan peranti.", listenOnlyTitle: "Latihan mendengar sahaja", listenOnlyUnavailable: "Semakan bacaan tidak tersedia di sini. Ketik Dengar, ulangi dengan suara kuat dan bandingkan dengan contoh.", listenOnlyAvailable: "Ketik Dengar dan ulangi dengan suara kuat. Benarkan mikrofon apabila bersedia untuk semakan.", readyMicrophone: "Saya bersedia — cuba dengan mikrofon", offlineTitle: "Tiada sambungan internet", offlineBody: "Semakan suara memerlukan sambungan pada kebanyakan peranti. Anda masih boleh berlatih dengan audio yang dimuat turun.", readNow: "Baca Sekarang", tapToRead: "Ketik, kemudian baca dengan suara kuat", listening: "Mendengar… Baca sekarang.", stop: "Henti — selesai", checking: "Menyemak bacaan anda…", errorLabels: { "no-speech": "Tiada pertuturan jelas dikesan", timeout: "Masa mendengar tamat", "not-allowed": "Kebenaran mikrofon tidak diberikan", network: "Perkhidmatan suara tidak dapat disambungkan", aborted: "Pengecaman dihentikan", unknown: "Ralat perkhidmatan suara tidak diketahui" } }),
  sindhi: copy({ advanced: "ترقي يافته", diagnosticsTitle: "آواز جي جاچ", diagnosticsDescription: "تازي آواز جي جاچ جي تفصيلي ڄاڻ.", recognizedText: "سڃاتل متن", score: "اسڪور", language: "ٻولي", confidence: "اعتماد", errors: "سڃاڻپ جون غلطيون", noErrors: "سڃاڻپ ۾ ڪا غلطي ناهي", close: "بند ڪريو", status: "حالت", unclearTitle: "مان اها ڳالهه صاف سمجهي نه سگهيس.", unclearBody: "ڪا ڳالهه ناهي — اها ڪوشش توهان خلاف شمار نه ٿيندي. ٻيهر ڪوشش ڪريو ۽ قدرتي نموني ڳالهايو.", retryTitle: "سٺي ڪوشش — اچو ته گڏجي بهتر ڪريون.", retryBody: "ٻيهر ٻڌو ۽ لفظ قدرتي نموني ورجايو. ٿورو پسمنظر جو شور ٺيڪ آهي.", passedExcellent: "بهترين! ماشاءالله!", passedCorrect: "شاباس! اهو صحيح هو.", wordMatch: "لفظ جي مطابقت", heard: "مون ٻڌو", focusSounds: "جن آوازن تي ڌيان ڏيو", extraSounds: "اضافي آواز", hearAgain: "ٻيهر ٻڌو", microphoneTitle: "مائڪروفون جي اجازت گهربل آهي", microphoneBody: "تلاوت جانچڻ لاءِ سيٽنگن ۾ مائڪروفون جي اجازت ڏيو. توهان صرف ٻڌي به مشق ڪري سگهو ٿا.", openSettings: "سيٽنگون کوليو", tryAgain: "ٻيهر ڪوشش", settingsFailed: "سيٽنگون پاڻمرادو نه کلي سگهيون. ڊوائيس جي سيٽنگن ۾ مائڪروفون جي اجازت ڏيو.", listenOnlyTitle: "صرف ٻڌڻ جي مشق", listenOnlyUnavailable: "هتي تلاوت جي جاچ موجود ناهي. ٻڌو، وڏي آواز سان ورجايو ۽ مثال سان ڀيٽيو.", listenOnlyAvailable: "ٻڌو ۽ وڏي آواز سان ورجايو. جاچ لاءِ تيار ٿيڻ تي مائڪروفون جي اجازت ڏيو.", readyMicrophone: "مان تيار آهيان — مائڪروفون سان آزمايو", offlineTitle: "انٽرنيٽ ڪنيڪشن ناهي", offlineBody: "اڪثر ڊوائيسن تي آواز جي جاچ لاءِ ڪنيڪشن گهرجي. ڊائونلوڊ ڪيل آڊيو سان مشق ڪريو.", readNow: "هاڻي پڙهو", tapToRead: "دٻايو، پوءِ وڏي آواز سان پڙهو", listening: "ٻڌي رهيو آهي… هاڻي پڙهو.", stop: "روڪيو — مڪمل ٿيو", checking: "توهان جي تلاوت جانچي پئي وڃي…", errorLabels: { "no-speech": "صاف ڳالهائڻ نه مليو", timeout: "ٻڌڻ جو وقت ختم ٿيو", "not-allowed": "مائڪروفون جي اجازت نه ملي", network: "آواز جي سروس سان رابطو نه ٿي سگهيو", aborted: "سڃاڻپ روڪي وئي", unknown: "آواز جي سروس جي اڻڄاتل غلطي" } }),
  persian: copy({ advanced: "پیشرفته", diagnosticsTitle: "تشخیص گفتار", diagnosticsDescription: "اطلاعات دقیق از آخرین بررسی گفتار.", recognizedText: "متن تشخیص‌داده‌شده", score: "امتیاز", language: "زبان", confidence: "اطمینان", errors: "خطاهای تشخیص", noErrors: "خطایی در تشخیص نیست", close: "بستن", status: "وضعیت", unclearTitle: "نتوانستم آن را واضح بفهمم.", unclearBody: "اشکالی ندارد — این تلاش علیه شما حساب نمی‌شود. دوباره امتحان کنید و طبیعی صحبت کنید.", retryTitle: "تلاش خوبی بود — با هم بهترش می‌کنیم.", retryBody: "دوباره گوش دهید و کلمه را طبیعی تکرار کنید. کمی صدای پس‌زمینه اشکالی ندارد.", passedExcellent: "عالی! ماشاءالله!", passedCorrect: "آفرین! درست بود.", wordMatch: "تطبیق کلمه", heard: "شنیدم", focusSounds: "صداهای نیازمند توجه", extraSounds: "صداهای اضافی شنیده‌شده", hearAgain: "دوباره گوش دهید", microphoneTitle: "اجازه میکروفون لازم است", microphoneBody: "برای بررسی قرائت، در تنظیمات اجازه میکروفون بدهید. می‌توانید فقط با گوش دادن تمرین کنید.", openSettings: "باز کردن تنظیمات", tryAgain: "دوباره امتحان کنید", settingsFailed: "تنظیمات به‌طور خودکار باز نشد. در تنظیمات دستگاه اجازه میکروفون بدهید.", listenOnlyTitle: "تمرین فقط با گوش دادن", listenOnlyUnavailable: "بررسی قرائت اینجا در دسترس نیست. گوش دهید، با صدای بلند تکرار کنید و با نمونه مقایسه کنید.", listenOnlyAvailable: "گوش دهید و با صدای بلند تکرار کنید. وقتی آماده بودید اجازه میکروفون بدهید.", readyMicrophone: "آماده‌ام — با میکروفون امتحان کن", offlineTitle: "اتصال اینترنت وجود ندارد", offlineBody: "بررسی گفتار در بیشتر دستگاه‌ها به اتصال نیاز دارد. با صدای دانلودشده تمرین کنید.", readNow: "اکنون بخوانید", tapToRead: "بزنید، سپس با صدای بلند بخوانید", listening: "در حال گوش دادن… اکنون بخوانید.", stop: "توقف — تمام شد", checking: "در حال بررسی قرائت شما…", errorLabels: { "no-speech": "گفتار واضحی تشخیص داده نشد", timeout: "زمان گوش دادن تمام شد", "not-allowed": "اجازه میکروفون داده نشد", network: "اتصال به سرویس گفتار ممکن نبود", aborted: "تشخیص متوقف شد", unknown: "خطای ناشناخته سرویس گفتار" } }),
  german: copy({ advanced: "Erweitert", diagnosticsTitle: "Sprachdiagnose", diagnosticsDescription: "Detaillierte Informationen der letzten Sprachprüfung.", recognizedText: "Erkannter Text", score: "Punktzahl", language: "Sprache", confidence: "Sicherheit", errors: "Erkennungsfehler", noErrors: "Keine Erkennungsfehler", close: "Schließen", status: "Status", unclearTitle: "Ich konnte das nicht deutlich verstehen.", unclearBody: "Kein Problem — das zählt nicht gegen dich. Versuche es erneut und sprich ganz natürlich.", retryTitle: "Guter Versuch — wir verbessern es gemeinsam.", retryBody: "Höre noch einmal zu und wiederhole das Wort natürlich. Etwas Hintergrundgeräusch ist in Ordnung.", passedExcellent: "Ausgezeichnet! Maschallah!", passedCorrect: "Gut gemacht! Das war richtig.", wordMatch: "Wortübereinstimmung", heard: "Gehört", focusSounds: "Laute zum Üben", extraSounds: "Zusätzlich gehörte Laute", hearAgain: "Noch einmal hören", microphoneTitle: "Mikrofonberechtigung erforderlich", microphoneBody: "Erlaube den Mikrofonzugriff in den Einstellungen, um deine Rezitation zu prüfen. Du kannst auch nur durch Zuhören üben.", openSettings: "Einstellungen öffnen", tryAgain: "Erneut versuchen", settingsFailed: "Die Einstellungen konnten nicht automatisch geöffnet werden. Erlaube das Mikrofon in den Geräteeinstellungen.", listenOnlyTitle: "Üben nur durch Zuhören", listenOnlyUnavailable: "Die Rezitationsprüfung ist hier nicht verfügbar. Höre zu, wiederhole laut und vergleiche mit dem Beispiel.", listenOnlyAvailable: "Höre zu und wiederhole laut. Erlaube das Mikrofon, wenn du bereit bist.", readyMicrophone: "Ich bin bereit — mit Mikrofon versuchen", offlineTitle: "Keine Internetverbindung", offlineBody: "Die Sprachprüfung benötigt auf den meisten Geräten eine Verbindung. Du kannst mit heruntergeladenem Audio üben.", readNow: "Jetzt lesen", tapToRead: "Tippen und laut lesen", listening: "Höre zu… Jetzt lesen.", stop: "Stopp — fertig", checking: "Rezitation wird geprüft…", errorLabels: { "no-speech": "Keine klare Sprache erkannt", timeout: "Zeitüberschreitung beim Zuhören", "not-allowed": "Mikrofonberechtigung nicht erteilt", network: "Sprachdienst konnte nicht verbunden werden", aborted: "Erkennung beendet", unknown: "Unbekannter Fehler des Sprachdienstes" } }),
  portuguese: copy({ ...english, advanced: "Avançado", diagnosticsTitle: "Diagnóstico de voz", diagnosticsDescription: "Informações detalhadas da última verificação de voz.", recognizedText: "Texto reconhecido", score: "Pontuação", language: "Idioma", confidence: "Confiança", errors: "Erros de reconhecimento", noErrors: "Nenhum erro de reconhecimento", close: "Fechar", status: "Estado", unclearTitle: "Não consegui entender com clareza.", unclearBody: "Não faz mal — isto não conta contra si. Tente novamente e fale naturalmente.", retryTitle: "Boa tentativa — vamos melhorar juntos.", retryBody: "Ouça novamente e repita a palavra naturalmente. Um pouco de ruído de fundo não faz mal.", passedExcellent: "Excelente! Mashallah!", passedCorrect: "Muito bem! Estava correto.", wordMatch: "Correspondência da palavra", heard: "Ouvi", focusSounds: "Sons a focar", extraSounds: "Sons adicionais ouvidos", hearAgain: "Ouvir novamente", microphoneTitle: "É necessária autorização do microfone", microphoneBody: "Para verificar a recitação, permita o microfone nas Definições. Também pode praticar apenas a ouvir.", openSettings: "Abrir Definições", tryAgain: "Tentar novamente", settingsFailed: "Não foi possível abrir as definições automaticamente. Permita o microfone nas definições do dispositivo.", listenOnlyTitle: "Prática apenas a ouvir", listenOnlyUnavailable: "A verificação não está disponível aqui. Ouça, repita em voz alta e compare com o exemplo.", listenOnlyAvailable: "Toque em Ouvir e repita em voz alta. Permita o microfone quando estiver pronto.", readyMicrophone: "Estou pronto — tentar com o microfone", offlineTitle: "Sem ligação à internet", offlineBody: "A verificação de voz precisa de ligação na maioria dos dispositivos. Pode praticar com áudio transferido.", readNow: "Ler agora", tapToRead: "Toque e leia em voz alta", listening: "A ouvir… Leia agora.", stop: "Parar — terminei", checking: "A verificar a sua recitação…", errorLabels: { "no-speech": "Não foi detetada fala clara", timeout: "O tempo de escuta terminou", "not-allowed": "A autorização do microfone não foi dada", network: "Não foi possível ligar ao serviço de voz", aborted: "Reconhecimento parado", unknown: "Erro desconhecido do serviço de voz" } }),
  russian: copy({ ...english, advanced: "Расширенные", diagnosticsTitle: "Диагностика речи", diagnosticsDescription: "Подробные сведения о последней проверке речи.", recognizedText: "Распознанный текст", score: "Оценка", language: "Язык", confidence: "Уверенность", errors: "Ошибки распознавания", noErrors: "Ошибок распознавания нет", close: "Закрыть", status: "Статус", unclearTitle: "Не удалось чётко это понять.", unclearBody: "Ничего страшного — это не засчитывается против вас. Попробуйте ещё раз и говорите естественно.", retryTitle: "Хорошая попытка — давайте улучшим её вместе.", retryBody: "Послушайте ещё раз и естественно повторите слово. Небольшой фоновый шум не помешает.", passedExcellent: "Отлично! Машаллах!", passedCorrect: "Хорошо! Это правильно.", wordMatch: "Совпадение слова", heard: "Я услышал", focusSounds: "Звуки для внимания", extraSounds: "Лишние услышанные звуки", hearAgain: "Послушать ещё раз", microphoneTitle: "Нужно разрешение микрофона", microphoneBody: "Чтобы проверить чтение, разрешите микрофон в настройках. Можно также заниматься только прослушиванием.", openSettings: "Открыть настройки", tryAgain: "Повторить", settingsFailed: "Не удалось автоматически открыть настройки. Разрешите микрофон в настройках устройства.", listenOnlyTitle: "Занятие только с прослушиванием", listenOnlyUnavailable: "Проверка чтения здесь недоступна. Послушайте, повторите вслух и сравните с примером.", listenOnlyAvailable: "Послушайте и повторите вслух. Разрешите микрофон, когда будете готовы.", readyMicrophone: "Я готов — попробовать с микрофоном", offlineTitle: "Нет подключения к интернету", offlineBody: "На большинстве устройств для проверки речи нужно подключение. Можно заниматься с загруженным аудио.", readNow: "Читать сейчас", tapToRead: "Нажмите и прочитайте вслух", listening: "Слушаю… Читайте сейчас.", stop: "Остановить — готово", checking: "Проверяем ваше чтение…", errorLabels: { "no-speech": "Чёткая речь не обнаружена", timeout: "Время прослушивания истекло", "not-allowed": "Разрешение микрофона не предоставлено", network: "Не удалось подключиться к речевой службе", aborted: "Распознавание остановлено", unknown: "Неизвестная ошибка речевой службы" } }),
  italian: copy({ ...english, advanced: "Avanzate", diagnosticsTitle: "Diagnostica vocale", diagnosticsDescription: "Informazioni dettagliate dall’ultimo controllo vocale.", recognizedText: "Testo riconosciuto", score: "Punteggio", language: "Lingua", confidence: "Affidabilità", errors: "Errori di riconoscimento", noErrors: "Nessun errore di riconoscimento", close: "Chiudi", status: "Stato", unclearTitle: "Non sono riuscito a capirlo chiaramente.", unclearBody: "Nessun problema — non conta contro di te. Riprova e parla in modo naturale.", retryTitle: "Buon tentativo — miglioriamolo insieme.", retryBody: "Ascolta di nuovo e ripeti la parola naturalmente. Un po’ di rumore di fondo va bene.", passedExcellent: "Eccellente! Mashallah!", passedCorrect: "Ben fatto! Era corretto.", wordMatch: "Corrispondenza della parola", heard: "Ho sentito", focusSounds: "Suoni su cui concentrarsi", extraSounds: "Suoni extra sentiti", hearAgain: "Ascolta di nuovo", microphoneTitle: "Serve il permesso del microfono", microphoneBody: "Per controllare la recitazione, consenti il microfono nelle impostazioni. Puoi anche esercitarti solo ascoltando.", openSettings: "Apri impostazioni", tryAgain: "Riprova", settingsFailed: "Impossibile aprire automaticamente le impostazioni. Consenti il microfono nelle impostazioni del dispositivo.", listenOnlyTitle: "Esercizio solo di ascolto", listenOnlyUnavailable: "Il controllo della recitazione non è disponibile qui. Ascolta, ripeti a voce alta e confronta con l’esempio.", listenOnlyAvailable: "Ascolta e ripeti a voce alta. Consenti il microfono quando sei pronto.", readyMicrophone: "Sono pronto — prova con il microfono", offlineTitle: "Nessuna connessione internet", offlineBody: "Il controllo vocale richiede una connessione sulla maggior parte dei dispositivi. Puoi esercitarti con l’audio scaricato.", readNow: "Leggi ora", tapToRead: "Tocca e leggi a voce alta", listening: "In ascolto… Leggi ora.", stop: "Ferma — ho finito", checking: "Controllo della recitazione…", errorLabels: { "no-speech": "Nessun parlato chiaro rilevato", timeout: "Tempo di ascolto scaduto", "not-allowed": "Permesso del microfono non concesso", network: "Impossibile connettersi al servizio vocale", aborted: "Riconoscimento interrotto", unknown: "Errore sconosciuto del servizio vocale" } }),
  chinese: copy({ ...english, advanced: "高级", diagnosticsTitle: "语音诊断", diagnosticsDescription: "最近一次语音检查的详细信息。", recognizedText: "识别文本", score: "分数", language: "语言", confidence: "置信度", errors: "识别错误", noErrors: "没有识别错误", close: "关闭", status: "状态", unclearTitle: "我没能清楚地听懂。", unclearBody: "没关系——这不会计入你的错误。请再试一次，自然地说话。", retryTitle: "做得不错——我们一起改进。", retryBody: "再听一次，自然地重复这个词。少量背景噪音没关系。", passedExcellent: "太棒了！真主保佑！", passedCorrect: "做得好！回答正确。", wordMatch: "词语匹配", heard: "我听到", focusSounds: "需要注意的音", extraSounds: "听到的额外音", hearAgain: "再听一次", microphoneTitle: "需要麦克风权限", microphoneBody: "要检查你的诵读，请在设置中允许使用麦克风。你也可以只听示范来练习。", openSettings: "打开设置", tryAgain: "再试一次", settingsFailed: "无法自动打开设置。请在设备设置中允许麦克风。", listenOnlyTitle: "只听练习", listenOnlyUnavailable: "这里无法检查诵读。点击聆听，大声重复，并与示范比较。", listenOnlyAvailable: "点击聆听并大声重复。准备检查时请允许麦克风。", readyMicrophone: "我准备好了——使用麦克风尝试", offlineTitle: "没有网络连接", offlineBody: "大多数设备需要网络才能进行语音检查。你仍可使用已下载的音频练习。", readNow: "现在朗读", tapToRead: "点击后大声朗读", listening: "正在聆听……现在朗读。", stop: "停止——我说完了", checking: "正在检查你的诵读……", errorLabels: { "no-speech": "未检测到清晰语音", timeout: "聆听超时", "not-allowed": "未获得麦克风权限", network: "无法连接语音服务", aborted: "识别已停止", unknown: "语音服务发生未知错误" } }),
  japanese: copy({ ...english, advanced: "詳細", diagnosticsTitle: "音声診断", diagnosticsDescription: "最新の音声チェックの詳細情報です。", recognizedText: "認識されたテキスト", score: "スコア", language: "言語", confidence: "信頼度", errors: "認識エラー", noErrors: "認識エラーはありません", close: "閉じる", status: "状態", unclearTitle: "はっきり聞き取れませんでした。", unclearBody: "大丈夫です。この結果は失敗として数えません。もう一度、自然に話してみてください。", retryTitle: "よくできました。一緒に改善しましょう。", retryBody: "もう一度聞いて、自然に単語を繰り返してください。少しの周囲の音は問題ありません。", passedExcellent: "すばらしい！マーシャーアッラー！", passedCorrect: "よくできました。正解です。", wordMatch: "単語の一致", heard: "聞き取った内容", focusSounds: "意識する音", extraSounds: "聞き取った余分な音", hearAgain: "もう一度聞く", microphoneTitle: "マイクの許可が必要です", microphoneBody: "朗読を確認するには、設定でマイクを許可してください。聞くだけの練習もできます。", openSettings: "設定を開く", tryAgain: "もう一度", settingsFailed: "設定を自動で開けませんでした。端末の設定でマイクを許可してください。", listenOnlyTitle: "聞くだけの練習", listenOnlyUnavailable: "ここでは朗読チェックを利用できません。聞いて、声に出して繰り返し、例と比べてください。", listenOnlyAvailable: "聞いて声に出して繰り返してください。準備ができたらマイクを許可してください。", readyMicrophone: "準備完了——マイクで試す", offlineTitle: "インターネット接続がありません", offlineBody: "多くの端末では音声チェックに接続が必要です。ダウンロードした音声で練習できます。", readNow: "今読む", tapToRead: "タップして声に出して読む", listening: "聞いています……今読んでください。", stop: "停止——終わりました", checking: "朗読を確認しています……", errorLabels: { "no-speech": "はっきりした音声を検出できませんでした", timeout: "聞き取りがタイムアウトしました", "not-allowed": "マイクの許可がありません", network: "音声サービスに接続できません", aborted: "認識を停止しました", unknown: "音声サービスの不明なエラー" } }),
  korean: copy({ ...english, advanced: "고급", diagnosticsTitle: "음성 진단", diagnosticsDescription: "최근 음성 확인의 자세한 정보입니다.", recognizedText: "인식된 텍스트", score: "점수", language: "언어", confidence: "신뢰도", errors: "인식 오류", noErrors: "인식 오류 없음", close: "닫기", status: "상태", unclearTitle: "명확하게 이해하지 못했어요.", unclearBody: "괜찮아요. 이 결과는 감점되지 않아요. 다시 자연스럽게 말해 보세요.", retryTitle: "잘 시도했어요. 함께 더 다듬어 봐요.", retryBody: "다시 듣고 단어를 자연스럽게 반복하세요. 약간의 주변 소음은 괜찮아요.", passedExcellent: "훌륭해요! 마샤알라!", passedCorrect: "잘했어요! 맞았습니다.", wordMatch: "단어 일치", heard: "들은 내용", focusSounds: "집중할 소리", extraSounds: "추가로 들린 소리", hearAgain: "다시 듣기", microphoneTitle: "마이크 권한이 필요해요", microphoneBody: "암송을 확인하려면 설정에서 마이크를 허용하세요. 듣기만 하며 연습할 수도 있어요.", openSettings: "설정 열기", tryAgain: "다시 시도", settingsFailed: "설정을 자동으로 열 수 없어요. 기기 설정에서 마이크를 허용하세요.", listenOnlyTitle: "듣기만 하는 연습", listenOnlyUnavailable: "여기서는 암송 확인을 이용할 수 없어요. 듣고 소리 내어 반복한 뒤 예시와 비교하세요.", listenOnlyAvailable: "듣고 소리 내어 반복하세요. 확인할 준비가 되면 마이크를 허용하세요.", readyMicrophone: "준비됐어요 — 마이크로 시도", offlineTitle: "인터넷 연결 없음", offlineBody: "대부분의 기기에서 음성 확인에는 연결이 필요해요. 다운로드한 오디오로 연습할 수 있어요.", readNow: "지금 읽기", tapToRead: "탭한 뒤 소리 내어 읽으세요", listening: "듣는 중… 지금 읽으세요.", stop: "중지 — 끝났어요", checking: "암송을 확인하는 중…", errorLabels: { "no-speech": "명확한 음성을 감지하지 못했어요", timeout: "듣기 시간이 초과됐어요", "not-allowed": "마이크 권한이 허용되지 않았어요", network: "음성 서비스에 연결할 수 없어요", aborted: "인식을 중지했어요", unknown: "음성 서비스의 알 수 없는 오류" } }),
  swahili: copy({ ...english, advanced: "Ya juu", diagnosticsTitle: "Uchunguzi wa sauti", diagnosticsDescription: "Maelezo ya kina kutoka ukaguzi wa mwisho wa sauti.", recognizedText: "Maandishi yaliyotambuliwa", score: "Alama", language: "Lugha", confidence: "Uhakika", errors: "Makosa ya utambuzi", noErrors: "Hakuna makosa ya utambuzi", close: "Funga", status: "Hali", unclearTitle: "Sikuweza kuelewa vizuri.", unclearBody: "Hakuna shida — hili halitahesabiwa dhidi yako. Jaribu tena na uzungumze kwa kawaida.", retryTitle: "Umejaribu vizuri — tuboreshe pamoja.", retryBody: "Sikiliza tena na urudie neno kwa kawaida. Kelele kidogo ya nyuma si tatizo.", passedExcellent: "Bora sana! Mashaallah!", passedCorrect: "Umefanya vizuri! Ilikuwa sahihi.", wordMatch: "Ulinganifu wa neno", heard: "Nimesikia", focusSounds: "Sauti za kuzingatia", extraSounds: "Sauti za ziada nilizosikia", hearAgain: "Sikiliza tena", microphoneTitle: "Ruhusa ya kipaza sauti inahitajika", microphoneBody: "Ili kuangalia usomaji wako, ruhusu kipaza sauti kwenye Mipangilio. Unaweza pia kufanya mazoezi kwa kusikiliza tu.", openSettings: "Fungua Mipangilio", tryAgain: "Jaribu Tena", settingsFailed: "Mipangilio haikuweza kufunguka kiotomatiki. Ruhusu kipaza sauti kwenye mipangilio ya kifaa.", listenOnlyTitle: "Mazoezi ya kusikiliza tu", listenOnlyUnavailable: "Ukaguzi wa usomaji haupatikani hapa. Sikiliza, rudia kwa sauti, na linganisha na mfano.", listenOnlyAvailable: "Sikiliza na rudia kwa sauti. Ruhusu kipaza sauti ukiwa tayari kukaguliwa.", readyMicrophone: "Niko tayari — jaribu kwa kipaza sauti", offlineTitle: "Hakuna muunganisho wa intaneti", offlineBody: "Ukaguzi wa sauti unahitaji muunganisho kwenye vifaa vingi. Bado unaweza kufanya mazoezi kwa sauti iliyopakuliwa.", readNow: "Soma Sasa", tapToRead: "Gusa, kisha soma kwa sauti", listening: "Nasikiliza… Soma sasa.", stop: "Simamisha — nimemaliza", checking: "Tunakagua usomaji wako…", errorLabels: { "no-speech": "Hakuna sauti wazi iliyotambuliwa", timeout: "Muda wa kusikiliza umeisha", "not-allowed": "Ruhusa ya kipaza sauti haikutolewa", network: "Huduma ya sauti haikuweza kuunganishwa", aborted: "Utambuzi umesimamishwa", unknown: "Hitilafu isiyojulikana ya huduma ya sauti" } }),
  tamil: copy({ ...english, advanced: "மேம்பட்டது", diagnosticsTitle: "குரல் கண்டறிதல்", diagnosticsDescription: "சமீபத்திய குரல் சரிபார்ப்பின் விரிவான தகவல்.", recognizedText: "அறியப்பட்ட உரை", score: "மதிப்பெண்", language: "மொழி", confidence: "நம்பிக்கை", errors: "அறிதல் பிழைகள்", noErrors: "அறிதல் பிழைகள் இல்லை", close: "மூடு", status: "நிலை", unclearTitle: "அதைத் தெளிவாகப் புரிந்துகொள்ள முடியவில்லை.", unclearBody: "பரவாயில்லை — இது உங்களுக்கு எதிராகக் கணக்கிடப்படாது. மீண்டும் முயற்சி செய்து இயல்பாகப் பேசுங்கள்.", retryTitle: "நல்ல முயற்சி — ஒன்றாக மேம்படுத்துவோம்.", retryBody: "மீண்டும் கேட்டு இயல்பாக வார்த்தையைச் சொல்லுங்கள். சிறிது பின்னணி சத்தம் பரவாயில்லை.", passedExcellent: "சிறப்பு! மாஷாஅல்லாஹ்!", passedCorrect: "நன்றாகச் செய்தீர்கள்! சரியாக இருந்தது.", wordMatch: "வார்த்தைப் பொருத்தம்", heard: "நான் கேட்டது", focusSounds: "கவனம் செலுத்த வேண்டிய ஒலிகள்", extraSounds: "கேட்ட கூடுதல் ஒலிகள்", hearAgain: "மீண்டும் கேளுங்கள்", microphoneTitle: "மைக்ரோஃபோன் அனுமதி தேவை", microphoneBody: "ஓதலைச் சரிபார்க்க, அமைப்புகளில் மைக்ரோஃபோனை அனுமதிக்கவும். கேட்பதன் மூலம் மட்டும் பயிற்சி செய்யலாம்.", openSettings: "அமைப்புகளைத் திற", tryAgain: "மீண்டும் முயற்சி", settingsFailed: "அமைப்புகளைத் தானாகத் திறக்க முடியவில்லை. சாதன அமைப்புகளில் மைக்ரோஃபோனை அனுமதிக்கவும்.", listenOnlyTitle: "கேட்பதன் மூலம் மட்டும் பயிற்சி", listenOnlyUnavailable: "ஓதல் சரிபார்ப்பு இங்கே கிடைக்கவில்லை. கேட்டு, சத்தமாகச் சொல்லி, எடுத்துக்காட்டுடன் ஒப்பிடுங்கள்.", listenOnlyAvailable: "கேட்டு சத்தமாகச் சொல்லுங்கள். சரிபார்க்கத் தயாரானதும் மைக்ரோஃபோனை அனுமதிக்கவும்.", readyMicrophone: "நான் தயார் — மைக்ரோஃபோனில் முயற்சி", offlineTitle: "இணைய இணைப்பு இல்லை", offlineBody: "பெரும்பாலான சாதனங்களில் குரல் சரிபார்ப்புக்கு இணைப்பு தேவை. பதிவிறக்கிய ஆடியோவில் பயிற்சி செய்யலாம்.", readNow: "இப்போது படியுங்கள்", tapToRead: "தட்டி சத்தமாகப் படியுங்கள்", listening: "கேட்கிறது… இப்போது படியுங்கள்.", stop: "நிறுத்து — முடிந்தது", checking: "உங்கள் ஓதல் சரிபார்க்கப்படுகிறது…", errorLabels: { "no-speech": "தெளிவான பேச்சு கண்டறியப்படவில்லை", timeout: "கேட்கும் நேரம் முடிந்தது", "not-allowed": "மைக்ரோஃபோன் அனுமதி வழங்கப்படவில்லை", network: "குரல் சேவையுடன் இணைக்க முடியவில்லை", aborted: "அறிதல் நிறுத்தப்பட்டது", unknown: "குரல் சேவையில் அறியப்படாத பிழை" } }),
  telugu: copy({ ...english, advanced: "అధునాతన", diagnosticsTitle: "వాయిస్ నిర్ధారణ", diagnosticsDescription: "తాజా వాయిస్ తనిఖీకి సంబంధించిన వివరాలు.", recognizedText: "గుర్తించిన వచనం", score: "స్కోర్", language: "భాష", confidence: "నమ్మకం", errors: "గుర్తింపు లోపాలు", noErrors: "గుర్తింపు లోపాలు లేవు", close: "మూసివేయి", status: "స్థితి", unclearTitle: "నాకు అది స్పష్టంగా అర్థం కాలేదు.", unclearBody: "పర్వాలేదు — ఇది మీకు వ్యతిరేకంగా లెక్కించబడదు. మళ్లీ ప్రయత్నించి సహజంగా మాట్లాడండి.", retryTitle: "మంచి ప్రయత్నం — కలిసి మెరుగుపరుచుకుందాం.", retryBody: "మళ్లీ విని పదాన్ని సహజంగా పలకండి. కొద్దిగా నేపథ్య శబ్దం పర్వాలేదు.", passedExcellent: "అద్భుతం! మాషా అల్లాహ్!", passedCorrect: "బాగా చేశారు! అది సరైనది.", wordMatch: "పద సరిపోలిక", heard: "నేను విన్నది", focusSounds: "దృష్టి పెట్టాల్సిన శబ్దాలు", extraSounds: "విన్న అదనపు శబ్దాలు", hearAgain: "మళ్లీ వినండి", microphoneTitle: "మైక్రోఫోన్ అనుమతి అవసరం", microphoneBody: "మీ పఠనాన్ని తనిఖీ చేయడానికి సెట్టింగ్‌లలో మైక్రోఫోన్‌ను అనుమతించండి. వినడం ద్వారా మాత్రమే కూడా సాధన చేయవచ్చు.", openSettings: "సెట్టింగ్‌లు తెరవండి", tryAgain: "మళ్లీ ప్రయత్నించండి", settingsFailed: "సెట్టింగ్‌లు స్వయంచాలకంగా తెరవబడలేదు. పరికర సెట్టింగ్‌లలో మైక్రోఫోన్‌ను అనుమతించండి.", listenOnlyTitle: "వినడం ద్వారా మాత్రమే సాధన", listenOnlyUnavailable: "పఠన తనిఖీ ఇక్కడ అందుబాటులో లేదు. వినండి, గట్టిగా పునరావృతం చేసి ఉదాహరణతో పోల్చండి.", listenOnlyAvailable: "విని గట్టిగా పునరావృతం చేయండి. తనిఖీకి సిద్ధమైనప్పుడు మైక్రోఫోన్‌ను అనుమతించండి.", readyMicrophone: "నేను సిద్ధం — మైక్రోఫోన్‌తో ప్రయత్నించండి", offlineTitle: "ఇంటర్నెట్ కనెక్షన్ లేదు", offlineBody: "చాలా పరికరాల్లో వాయిస్ తనిఖీకి కనెక్షన్ అవసరం. డౌన్‌లోడ్ చేసిన ఆడియోతో సాధన చేయవచ్చు.", readNow: "ఇప్పుడు చదవండి", tapToRead: "నొక్కి గట్టిగా చదవండి", listening: "వింటోంది… ఇప్పుడు చదవండి.", stop: "ఆపు — పూర్తయింది", checking: "మీ పఠనాన్ని తనిఖీ చేస్తోంది…", errorLabels: { "no-speech": "స్పష్టమైన మాట గుర్తించబడలేదు", timeout: "వినే సమయం ముగిసింది", "not-allowed": "మైక్రోఫోన్ అనుమతి ఇవ్వలేదు", network: "వాయిస్ సేవకు కనెక్ట్ కాలేదు", aborted: "గుర్తింపు ఆపబడింది", unknown: "వాయిస్ సేవలో తెలియని లోపం" } }),
  malayalam: copy({ ...english, advanced: "വിപുലമായത്", diagnosticsTitle: "ശബ്ദ പരിശോധന", diagnosticsDescription: "ഏറ്റവും പുതിയ ശബ്ദ പരിശോധനയുടെ വിശദാംശങ്ങൾ.", recognizedText: "തിരിച്ചറിഞ്ഞ വാചകം", score: "സ്കോർ", language: "ഭാഷ", confidence: "വിശ്വാസം", errors: "തിരിച്ചറിയൽ പിശകുകൾ", noErrors: "തിരിച്ചറിയൽ പിശകുകളില്ല", close: "അടയ്ക്കുക", status: "നില", unclearTitle: "അത് വ്യക്തമായി മനസ്സിലാക്കാനായില്ല.", unclearBody: "കുഴപ്പമില്ല — ഇത് നിങ്ങൾക്കെതിരെ കണക്കാക്കില്ല. വീണ്ടും ശ്രമിച്ച് സ്വാഭാവികമായി സംസാരിക്കുക.", retryTitle: "നല്ല ശ്രമം — നമുക്ക് ഒരുമിച്ച് മെച്ചപ്പെടുത്താം.", retryBody: "വീണ്ടും കേട്ട് വാക്ക് സ്വാഭാവികമായി ആവർത്തിക്കുക. ചെറിയ പശ്ചാത്തല ശബ്ദം പ്രശ്നമല്ല.", passedExcellent: "മികച്ചത്! മാഷാ അല്ലാഹ്!", passedCorrect: "നന്നായി! അത് ശരിയായിരുന്നു.", wordMatch: "വാക്ക് പൊരുത്തം", heard: "ഞാൻ കേട്ടത്", focusSounds: "ശ്രദ്ധിക്കേണ്ട ശബ്ദങ്ങൾ", extraSounds: "കേട്ട അധിക ശബ്ദങ്ങൾ", hearAgain: "വീണ്ടും കേൾക്കുക", microphoneTitle: "മൈക്രോഫോൺ അനുമതി ആവശ്യമാണ്", microphoneBody: "പാരായണം പരിശോധിക്കാൻ ക്രമീകരണങ്ങളിൽ മൈക്രോഫോൺ അനുവദിക്കുക. കേൾക്കുക മാത്രം ചെയ്തും പരിശീലിക്കാം.", openSettings: "ക്രമീകരണങ്ങൾ തുറക്കുക", tryAgain: "വീണ്ടും ശ്രമിക്കുക", settingsFailed: "ക്രമീകരണങ്ങൾ സ്വയം തുറക്കാനായില്ല. ഉപകരണ ക്രമീകരണങ്ങളിൽ മൈക്രോഫോൺ അനുവദിക്കുക.", listenOnlyTitle: "കേൾക്കുക മാത്രം ചെയ്തുള്ള പരിശീലനം", listenOnlyUnavailable: "പാരായണ പരിശോധന ഇവിടെ ലഭ്യമല്ല. കേൾക്കുക, ഉച്ചത്തിൽ ആവർത്തിക്കുക, ഉദാഹരണവുമായി താരതമ്യം ചെയ്യുക.", listenOnlyAvailable: "കേട്ട് ഉച്ചത്തിൽ ആവർത്തിക്കുക. പരിശോധനയ്ക്ക് തയ്യാറാകുമ്പോൾ മൈക്രോഫോൺ അനുവദിക്കുക.", readyMicrophone: "ഞാൻ തയ്യാറാണ് — മൈക്രോഫോണിൽ ശ്രമിക്കുക", offlineTitle: "ഇന്റർനെറ്റ് കണക്ഷനില്ല", offlineBody: "മിക്ക ഉപകരണങ്ങളിലും ശബ്ദ പരിശോധനയ്ക്ക് കണക്ഷൻ ആവശ്യമാണ്. ഡൗൺലോഡ് ചെയ്ത ഓഡിയോ ഉപയോഗിച്ച് പരിശീലിക്കാം.", readNow: "ഇപ്പോൾ വായിക്കുക", tapToRead: "ടാപ്പ് ചെയ്ത് ഉച്ചത്തിൽ വായിക്കുക", listening: "കേൾക്കുന്നു… ഇപ്പോൾ വായിക്കുക.", stop: "നിർത്തുക — പൂർത്തിയായി", checking: "നിങ്ങളുടെ പാരായണം പരിശോധിക്കുന്നു…", errorLabels: { "no-speech": "വ്യക്തമായ സംസാരം കണ്ടെത്തിയില്ല", timeout: "കേൾക്കാനുള്ള സമയം കഴിഞ്ഞു", "not-allowed": "മൈക്രോഫോൺ അനുമതി നൽകിയില്ല", network: "ശബ്ദ സേവനവുമായി ബന്ധപ്പെടാനായില്ല", aborted: "തിരിച്ചറിയൽ നിർത്തി", unknown: "ശബ്ദ സേവനത്തിലെ അജ്ഞാത പിശക്" } }),
  punjabi: copy({ ...english, advanced: "ਉੱਨਤ", diagnosticsTitle: "ਆਵਾਜ਼ ਜਾਂਚ", diagnosticsDescription: "ਤਾਜ਼ਾ ਆਵਾਜ਼ ਜਾਂਚ ਦੀ ਵਿਸਥਾਰ ਜਾਣਕਾਰੀ।", recognizedText: "ਪਛਾਣਿਆ ਪਾਠ", score: "ਸਕੋਰ", language: "ਭਾਸ਼ਾ", confidence: "ਭਰੋਸਾ", errors: "ਪਛਾਣ ਦੀਆਂ ਗਲਤੀਆਂ", noErrors: "ਪਛਾਣ ਦੀ ਕੋਈ ਗਲਤੀ ਨਹੀਂ", close: "ਬੰਦ ਕਰੋ", status: "ਸਥਿਤੀ", unclearTitle: "ਮੈਂ ਇਸਨੂੰ ਸਾਫ਼ ਨਹੀਂ ਸਮਝ ਸਕਿਆ।", unclearBody: "ਕੋਈ ਗੱਲ ਨਹੀਂ — ਇਹ ਤੁਹਾਡੇ ਵਿਰੁੱਧ ਨਹੀਂ ਗਿਣਿਆ ਜਾਵੇਗਾ। ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ ਅਤੇ ਕੁਦਰਤੀ ਬੋਲੋ।", retryTitle: "ਚੰਗੀ ਕੋਸ਼ਿਸ਼ — ਆਓ ਮਿਲ ਕੇ ਸੁਧਾਰੀਏ।", retryBody: "ਦੁਬਾਰਾ ਸੁਣੋ ਅਤੇ ਸ਼ਬਦ ਕੁਦਰਤੀ ਢੰਗ ਨਾਲ ਦੁਹਰਾਓ। ਥੋੜ੍ਹਾ ਪਿੱਛੋਕੜ ਦਾ ਸ਼ੋਰ ਠੀਕ ਹੈ।", passedExcellent: "ਸ਼ਾਨਦਾਰ! ਮਾਸ਼ਾਅੱਲਾਹ!", passedCorrect: "ਵਧੀਆ! ਇਹ ਸਹੀ ਸੀ।", wordMatch: "ਸ਼ਬਦ ਮਿਲਾਨ", heard: "ਮੈਂ ਸੁਣਿਆ", focusSounds: "ਧਿਆਨ ਦੇਣ ਵਾਲੀਆਂ ਆਵਾਜ਼ਾਂ", extraSounds: "ਵਾਧੂ ਸੁਣੀਆਂ ਆਵਾਜ਼ਾਂ", hearAgain: "ਦੁਬਾਰਾ ਸੁਣੋ", microphoneTitle: "ਮਾਈਕ੍ਰੋਫ਼ੋਨ ਦੀ ਇਜਾਜ਼ਤ ਚਾਹੀਦੀ ਹੈ", microphoneBody: "ਪਾਠ ਦੀ ਜਾਂਚ ਲਈ ਸੈਟਿੰਗਾਂ ਵਿੱਚ ਮਾਈਕ੍ਰੋਫ਼ੋਨ ਦੀ ਇਜਾਜ਼ਤ ਦਿਓ। ਤੁਸੀਂ ਸਿਰਫ਼ ਸੁਣ ਕੇ ਵੀ ਅਭਿਆਸ ਕਰ ਸਕਦੇ ਹੋ।", openSettings: "ਸੈਟਿੰਗਾਂ ਖੋਲ੍ਹੋ", tryAgain: "ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼", settingsFailed: "ਸੈਟਿੰਗਾਂ ਆਪਣੇ ਆਪ ਨਹੀਂ ਖੁੱਲ੍ਹੀਆਂ। ਡਿਵਾਈਸ ਸੈਟਿੰਗਾਂ ਵਿੱਚ ਮਾਈਕ੍ਰੋਫ਼ੋਨ ਦੀ ਇਜਾਜ਼ਤ ਦਿਓ।", listenOnlyTitle: "ਸਿਰਫ਼ ਸੁਣਨ ਦਾ ਅਭਿਆਸ", listenOnlyUnavailable: "ਇੱਥੇ ਪਾਠ ਜਾਂਚ ਉਪਲਬਧ ਨਹੀਂ। ਸੁਣੋ, ਉੱਚੀ ਆਵਾਜ਼ ਵਿੱਚ ਦੁਹਰਾਓ ਅਤੇ ਉਦਾਹਰਨ ਨਾਲ ਮਿਲਾਓ।", listenOnlyAvailable: "ਸੁਣੋ ਅਤੇ ਉੱਚੀ ਆਵਾਜ਼ ਵਿੱਚ ਦੁਹਰਾਓ। ਜਾਂਚ ਲਈ ਤਿਆਰ ਹੋਣ 'ਤੇ ਮਾਈਕ੍ਰੋਫ਼ੋਨ ਦੀ ਇਜਾਜ਼ਤ ਦਿਓ।", readyMicrophone: "ਮੈਂ ਤਿਆਰ ਹਾਂ — ਮਾਈਕ੍ਰੋਫ਼ੋਨ ਨਾਲ ਕੋਸ਼ਿਸ਼", offlineTitle: "ਇੰਟਰਨੈੱਟ ਕਨੈਕਸ਼ਨ ਨਹੀਂ", offlineBody: "ਜ਼ਿਆਦਾਤਰ ਡਿਵਾਈਸਾਂ 'ਤੇ ਆਵਾਜ਼ ਜਾਂਚ ਲਈ ਕਨੈਕਸ਼ਨ ਚਾਹੀਦਾ ਹੈ। ਡਾਊਨਲੋਡ ਕੀਤੇ ਆਡੀਓ ਨਾਲ ਅਭਿਆਸ ਕਰ ਸਕਦੇ ਹੋ।", readNow: "ਹੁਣ ਪੜ੍ਹੋ", tapToRead: "ਟੈਪ ਕਰੋ, ਫਿਰ ਉੱਚੀ ਆਵਾਜ਼ ਵਿੱਚ ਪੜ੍ਹੋ", listening: "ਸੁਣ ਰਿਹਾ ਹੈ… ਹੁਣ ਪੜ੍ਹੋ।", stop: "ਰੋਕੋ — ਹੋ ਗਿਆ", checking: "ਤੁਹਾਡਾ ਪਾਠ ਜਾਂਚਿਆ ਜਾ ਰਿਹਾ ਹੈ…", errorLabels: { "no-speech": "ਸਾਫ਼ ਬੋਲਣ ਦੀ ਪਛਾਣ ਨਹੀਂ ਹੋਈ", timeout: "ਸੁਣਨ ਦਾ ਸਮਾਂ ਖਤਮ", "not-allowed": "ਮਾਈਕ੍ਰੋਫ਼ੋਨ ਦੀ ਇਜਾਜ਼ਤ ਨਹੀਂ ਮਿਲੀ", network: "ਆਵਾਜ਼ ਸੇਵਾ ਨਾਲ ਜੁੜ ਨਹੀਂ ਸਕੇ", aborted: "ਪਛਾਣ ਰੋਕੀ ਗਈ", unknown: "ਆਵਾਜ਼ ਸੇਵਾ ਦੀ ਅਣਜਾਣ ਗਲਤੀ" } }),
  dutch: copy({ ...english, advanced: "Geavanceerd", diagnosticsTitle: "Spraakdiagnose", diagnosticsDescription: "Uitgebreide informatie van de laatste spraakcontrole.", recognizedText: "Herkende tekst", score: "Score", language: "Taal", confidence: "Zekerheid", errors: "Herkenningsfouten", noErrors: "Geen herkenningsfouten", close: "Sluiten", status: "Status", unclearTitle: "Ik kon het niet duidelijk verstaan.", unclearBody: "Geen probleem — dit telt niet tegen je. Probeer het opnieuw en spreek natuurlijk.", retryTitle: "Goede poging — laten we het samen verbeteren.", retryBody: "Luister opnieuw en herhaal het woord natuurlijk. Een beetje achtergrondgeluid is prima.", passedExcellent: "Uitstekend! Mashallah!", passedCorrect: "Goed gedaan! Dat was correct.", wordMatch: "Woordovereenkomst", heard: "Ik hoorde", focusSounds: "Klanken om op te letten", extraSounds: "Extra gehoorde klanken", hearAgain: "Opnieuw luisteren", microphoneTitle: "Microfoontoestemming nodig", microphoneBody: "Sta de microfoon toe in Instellingen om je recitatie te controleren. Je kunt ook alleen luisterend oefenen.", openSettings: "Instellingen openen", tryAgain: "Opnieuw proberen", settingsFailed: "Instellingen konden niet automatisch worden geopend. Sta de microfoon toe in de apparaatinstellingen.", listenOnlyTitle: "Oefenen met alleen luisteren", listenOnlyUnavailable: "Recitatiecontrole is hier niet beschikbaar. Luister, herhaal hardop en vergelijk met het voorbeeld.", listenOnlyAvailable: "Luister en herhaal hardop. Sta de microfoon toe wanneer je klaar bent.", readyMicrophone: "Ik ben klaar — probeer met de microfoon", offlineTitle: "Geen internetverbinding", offlineBody: "Spraakcontrole vereist op de meeste apparaten een verbinding. Je kunt oefenen met gedownloade audio.", readNow: "Nu lezen", tapToRead: "Tik en lees hardop", listening: "Luisteren… Lees nu.", stop: "Stoppen — klaar", checking: "Je recitatie wordt gecontroleerd…", errorLabels: { "no-speech": "Geen duidelijke spraak gedetecteerd", timeout: "Luistertijd verlopen", "not-allowed": "Microfoontoestemming niet gegeven", network: "Kan geen verbinding maken met de spraakdienst", aborted: "Herkenning gestopt", unknown: "Onbekende fout van de spraakdienst" } }),
  thai: copy({ ...english, advanced: "ขั้นสูง", diagnosticsTitle: "การวินิจฉัยเสียง", diagnosticsDescription: "ข้อมูลโดยละเอียดจากการตรวจเสียงครั้งล่าสุด", recognizedText: "ข้อความที่รู้จำได้", score: "คะแนน", language: "ภาษา", confidence: "ความมั่นใจ", errors: "ข้อผิดพลาดในการรู้จำ", noErrors: "ไม่มีข้อผิดพลาดในการรู้จำ", close: "ปิด", status: "สถานะ", unclearTitle: "ฉันฟังไม่ชัดเจน", unclearBody: "ไม่เป็นไร — จะไม่คิดคะแนนความผิดพลาด ลองอีกครั้งและพูดตามธรรมชาติ", retryTitle: "พยายามได้ดี — มาปรับปรุงไปด้วยกัน", retryBody: "ฟังอีกครั้งแล้วพูดคำนี้ตามธรรมชาติ เสียงรบกวนเล็กน้อยไม่เป็นไร", passedExcellent: "ยอดเยี่ยม! มาชาอัลลอฮ์!", passedCorrect: "ทำได้ดี! ถูกต้อง", wordMatch: "ความตรงกันของคำ", heard: "สิ่งที่ได้ยิน", focusSounds: "เสียงที่ควรเน้น", extraSounds: "เสียงเพิ่มเติมที่ได้ยิน", hearAgain: "ฟังอีกครั้ง", microphoneTitle: "ต้องอนุญาตไมโครโฟน", microphoneBody: "เพื่อ ตรวจการอ่านของคุณ ให้อนุญาตไมโครโฟนในการตั้งค่า คุณยังฝึกด้วยการฟังอย่างเดียวได้", openSettings: "เปิดการตั้งค่า", tryAgain: "ลองอีกครั้ง", settingsFailed: "เปิดการตั้งค่าอัตโนมัติไม่ได้ โปรดอนุญาตไมโครโฟนในการตั้งค่าอุปกรณ์", listenOnlyTitle: "ฝึกด้วยการฟังอย่างเดียว", listenOnlyUnavailable: "ไม่สามารถตรวจการอ่านที่นี่ได้ แตะฟัง พูดตามเสียงดัง และเปรียบเทียบกับตัวอย่าง", listenOnlyAvailable: "แตะฟังแล้วพูดตามเสียงดัง อนุญาตไมโครโฟนเมื่อพร้อมตรวจ", readyMicrophone: "พร้อมแล้ว — ลองใช้ไมโครโฟน", offlineTitle: "ไม่มีการเชื่อมต่ออินเทอร์เน็ต", offlineBody: "อุปกรณ์ส่วนใหญ่ต้องเชื่อมต่อเพื่อตรวจเสียง คุณยังฝึกด้วยเสียงที่ดาวน์โหลดไว้ได้", readNow: "อ่านตอนนี้", tapToRead: "แตะแล้วอ่านออกเสียง", listening: "กำลังฟัง… อ่านได้เลย", stop: "หยุด — เสร็จแล้ว", checking: "กำลังตรวจการอ่านของคุณ…", errorLabels: { "no-speech": "ไม่พบเสียงพูดที่ชัดเจน", timeout: "หมดเวลาฟัง", "not-allowed": "ไม่ได้รับอนุญาตให้ใช้ไมโครโฟน", network: "เชื่อมต่อบริการเสียงไม่ได้", aborted: "หยุดการรู้จำแล้ว", unknown: "ข้อผิดพลาดที่ไม่ทราบสาเหตุของบริการเสียง" } }),
  vietnamese: copy({ ...english, advanced: "Nâng cao", diagnosticsTitle: "Chẩn đoán giọng nói", diagnosticsDescription: "Thông tin chi tiết từ lần kiểm tra giọng nói gần nhất.", recognizedText: "Văn bản đã nhận dạng", score: "Điểm", language: "Ngôn ngữ", confidence: "Độ tin cậy", errors: "Lỗi nhận dạng", noErrors: "Không có lỗi nhận dạng", close: "Đóng", status: "Trạng thái", unclearTitle: "Tôi chưa thể nghe rõ điều đó.", unclearBody: "Không sao — lần này không tính là lỗi của bạn. Hãy thử lại và nói tự nhiên.", retryTitle: "Bạn đã cố gắng tốt — cùng cải thiện nhé.", retryBody: "Nghe lại và lặp lại từ đó một cách tự nhiên. Một chút tiếng ồn nền không sao.", passedExcellent: "Tuyệt vời! Mashallah!", passedCorrect: "Làm tốt lắm! Chính xác rồi.", wordMatch: "Độ khớp từ", heard: "Tôi nghe thấy", focusSounds: "Âm cần chú ý", extraSounds: "Âm thừa đã nghe", hearAgain: "Nghe lại", microphoneTitle: "Cần cấp quyền micro", microphoneBody: "Để kiểm tra phần đọc, hãy cho phép micro trong Cài đặt. Bạn vẫn có thể luyện tập chỉ bằng cách nghe.", openSettings: "Mở Cài đặt", tryAgain: "Thử lại", settingsFailed: "Không thể tự mở Cài đặt. Hãy cho phép micro trong cài đặt thiết bị.", listenOnlyTitle: "Luyện tập chỉ nghe", listenOnlyUnavailable: "Không thể kiểm tra phần đọc ở đây. Hãy nghe, lặp lại thành tiếng và so sánh với ví dụ.", listenOnlyAvailable: "Hãy nghe và lặp lại thành tiếng. Cho phép micro khi bạn sẵn sàng kiểm tra.", readyMicrophone: "Tôi sẵn sàng — thử bằng micro", offlineTitle: "Không có kết nối internet", offlineBody: "Hầu hết thiết bị cần kết nối để kiểm tra giọng nói. Bạn vẫn có thể luyện với âm thanh đã tải.", readNow: "Đọc ngay", tapToRead: "Chạm rồi đọc thành tiếng", listening: "Đang nghe… Hãy đọc ngay.", stop: "Dừng — tôi đã xong", checking: "Đang kiểm tra phần đọc…", errorLabels: { "no-speech": "Không phát hiện lời nói rõ ràng", timeout: "Hết thời gian nghe", "not-allowed": "Chưa cấp quyền micro", network: "Không thể kết nối dịch vụ giọng nói", aborted: "Đã dừng nhận dạng", unknown: "Lỗi không xác định của dịch vụ giọng nói" } }),
  azerbaijani: copy({ ...english, advanced: "Təkmil", diagnosticsTitle: "Nitq diaqnostikası", diagnosticsDescription: "Son nitq yoxlamasından ətraflı məlumat.", recognizedText: "Tanındı mətn", score: "Bal", language: "Dil", confidence: "Əminlik", errors: "Tanıma xətaları", noErrors: "Tanıma xətası yoxdur", close: "Bağla", status: "Vəziyyət", unclearTitle: "Bunu aydın başa düşə bilmədim.", unclearBody: "Narahat olmayın — bu cəhd sizə qarşı hesablanmır. Yenidən cəhd edin və təbii danışın.", retryTitle: "Yaxşı cəhd — gəlin birlikdə düzəldək.", retryBody: "Yenidən dinləyin və sözü təbii şəkildə təkrarlayın. Bir az fon səsi problem deyil.", passedExcellent: "Əla! Maşallah!", passedCorrect: "Afərin! Düzgün idi.", wordMatch: "Söz uyğunluğu", heard: "Eşitdiyim", focusSounds: "Diqqət ediləcək səslər", extraSounds: "Eşitdiyim əlavə səslər", hearAgain: "Yenidən dinlə", microphoneTitle: "Mikrofon icazəsi lazımdır", microphoneBody: "Oxunuşu yoxlamaq üçün Ayarlarda mikrofona icazə verin. Yalnız dinləməklə də məşq edə bilərsiniz.", openSettings: "Ayarları aç", tryAgain: "Yenidən cəhd", settingsFailed: "Ayarları avtomatik açmaq olmadı. Cihaz ayarlarında mikrofona icazə verin.", listenOnlyTitle: "Yalnız dinləmə məşqi", listenOnlyUnavailable: "Oxunuş yoxlaması burada mövcud deyil. Dinləyin, ucadan təkrarlayın və nümunə ilə müqayisə edin.", listenOnlyAvailable: "Dinləyin və ucadan təkrarlayın. Yoxlamaya hazır olduqda mikrofona icazə verin.", readyMicrophone: "Hazıram — mikrofonla cəhd et", offlineTitle: "İnternet bağlantısı yoxdur", offlineBody: "Əksər cihazlarda nitq yoxlaması üçün bağlantı lazımdır. Yüklənmiş səslə məşq edə bilərsiniz.", readNow: "İndi oxu", tapToRead: "Toxun və ucadan oxuyun", listening: "Dinləyir… İndi oxuyun.", stop: "Dayandır — bitirdim", checking: "Oxunuşunuz yoxlanılır…", errorLabels: { "no-speech": "Aydın nitq aşkarlanmadı", timeout: "Dinləmə vaxtı bitdi", "not-allowed": "Mikrofon icazəsi verilmədi", network: "Nitq xidmətinə qoşulmaq olmadı", aborted: "Tanıma dayandırıldı", unknown: "Nitq xidmətində naməlum xəta" } }),
  bosnian: copy({ ...english, advanced: "Napredno", diagnosticsTitle: "Dijagnostika govora", diagnosticsDescription: "Detaljne informacije iz posljednje provjere govora.", recognizedText: "Prepoznati tekst", score: "Rezultat", language: "Jezik", confidence: "Pouzdanost", errors: "Greške prepoznavanja", noErrors: "Nema grešaka prepoznavanja", close: "Zatvori", status: "Status", unclearTitle: "Nisam to jasno razumio.", unclearBody: "Nema veze — ovo se ne računa protiv vas. Pokušajte ponovo i govorite prirodno.", retryTitle: "Dobar pokušaj — poboljšajmo ga zajedno.", retryBody: "Poslušajte ponovo i prirodno ponovite riječ. Malo pozadinske buke nije problem.", passedExcellent: "Odlično! Mašallah!", passedCorrect: "Bravo! Bilo je tačno.", wordMatch: "Podudaranje riječi", heard: "Čuo sam", focusSounds: "Glasovi na koje treba obratiti pažnju", extraSounds: "Dodatni čuti glasovi", hearAgain: "Poslušaj ponovo", microphoneTitle: "Potrebna je dozvola za mikrofon", microphoneBody: "Da provjerimo učenje, dozvolite mikrofon u Postavkama. Možete vježbati i samo slušanjem.", openSettings: "Otvori Postavke", tryAgain: "Pokušaj ponovo", settingsFailed: "Postavke se nisu mogle automatski otvoriti. Dozvolite mikrofon u postavkama uređaja.", listenOnlyTitle: "Vježba samo slušanjem", listenOnlyUnavailable: "Provjera učenja ovdje nije dostupna. Slušajte, ponovite naglas i uporedite s primjerom.", listenOnlyAvailable: "Slušajte i ponovite naglas. Dozvolite mikrofon kada budete spremni.", readyMicrophone: "Spreman sam — pokušaj s mikrofonom", offlineTitle: "Nema internet veze", offlineBody: "Provjera govora na većini uređaja zahtijeva vezu. Možete vježbati s preuzetim zvukom.", readNow: "Čitaj sada", tapToRead: "Dodirni pa čitaj naglas", listening: "Slušam… Čitaj sada.", stop: "Zaustavi — završio sam", checking: "Provjeravamo vaše učenje…", errorLabels: { "no-speech": "Nije otkriven jasan govor", timeout: "Vrijeme slušanja je isteklo", "not-allowed": "Dozvola za mikrofon nije data", network: "Nije moguće povezati se s govornom uslugom", aborted: "Prepoznavanje zaustavljeno", unknown: "Nepoznata greška govorne usluge" } }),
  somali: copy({ ...english, advanced: "Sare", diagnosticsTitle: "Baadhista codka", diagnosticsDescription: "Macluumaad faahfaahsan oo ka yimid hubintii codka ee u dambaysay.", recognizedText: "Qoraalka la aqoonsaday", score: "Dhibco", language: "Luqad", confidence: "Kalsooni", errors: "Khaladaadka aqoonsiga", noErrors: "Khalad aqoonsi ma jiro", close: "Xir", status: "Xaalad", unclearTitle: "Si cad uma fahmin taas.", unclearBody: "Dhib ma leh — tani laguguma xisaabinayo. Mar kale isku day oo si dabiici ah u hadal.", retryTitle: "Isku day fiican — aan wada hagaajino.", retryBody: "Mar kale dhegayso oo erayga si dabiici ah ugu celi. Qaylo yar oo gadaal ah dhib ma leh.", passedExcellent: "Aad u fiican! Maasha Allah!", passedCorrect: "Waa hagaag! Waa sax.", wordMatch: "Iswaafajinta erayga", heard: "Waxaan maqlay", focusSounds: "Codadka la saaro", extraSounds: "Codad dheeraad ah oo la maqlay", hearAgain: "Mar kale dhegayso", microphoneTitle: "Oggolaanshaha makarafoonka ayaa loo baahan yahay", microphoneBody: "Si loo hubiyo akhriskaaga, oggolow makarafoonka Dejinta. Waxaad sidoo kale ku tababaran kartaa dhegaysi oo keliya.", openSettings: "Fur Dejinta", tryAgain: "Mar kale isku day", settingsFailed: "Dejinta si toos ah looma furi karin. Oggolow makarafoonka dejinta qalabka.", listenOnlyTitle: "Tababar dhegaysi oo keliya", listenOnlyUnavailable: "Hubinta akhrisku halkan kama shaqayso. Dhegayso, cod dheer ku celi, oo tusaalaha la barbar dhig.", listenOnlyAvailable: "Dhegayso oo cod dheer ku celi. Oggolow makarafoonka markaad diyaar tahay.", readyMicrophone: "Waan diyaar ahay — makarafoonka ku tijaabi", offlineTitle: "Internet ma jiro", offlineBody: "Hubinta codku qalabyada badankood waxay u baahan tahay xiriir. Waxaad ku tababaran kartaa cod la soo dejiyey.", readNow: "Hadda akhri", tapToRead: "Taabo, dabadeed cod dheer ku akhri", listening: "Waan dhegaysanayaa… Hadda akhri.", stop: "Jooji — waan dhammeeyey", checking: "Akhriskaaga ayaa la hubinayaa…", errorLabels: { "no-speech": "Hadal cad lama helin", timeout: "Waqtigii dhegaysigu wuu dhammaaday", "not-allowed": "Oggolaanshaha makarafoonka lama siin", network: "Adeegga codka lama xiriirin", aborted: "Aqoonsigii waa la joojiyey", unknown: "Khalad aan la garanayn oo adeegga codka ah" } }),
  hausa: copy({ ...english, advanced: "Na gaba", diagnosticsTitle: "Binciken murya", diagnosticsDescription: "Cikakken bayani daga binciken murya na ƙarshe.", recognizedText: "Rubutun da aka gane", score: "Maki", language: "Harshe", confidence: "Aminci", errors: "Kurakuran ganewa", noErrors: "Babu kuskuren ganewa", close: "Rufe", status: "Matsayi", unclearTitle: "Ban fahimci hakan sosai ba.", unclearBody: "Ba damuwa — ba za a ƙirga wannan a kanku ba. Sake gwadawa kuma ku yi magana a dabi'a.", retryTitle: "Kokari mai kyau — mu inganta shi tare.", retryBody: "Sake sauraro kuma ku maimaita kalmar a dabi'a. Ƙaramin hayaniyar baya ba matsala ba ce.", passedExcellent: "Madalla! Masha Allah!", passedCorrect: "Aiki mai kyau! Daidai ne.", wordMatch: "Daidaituwar kalma", heard: "Na ji", focusSounds: "Sautin da za a mai da hankali", extraSounds: "Ƙarin sautunan da na ji", hearAgain: "Sake sauraro", microphoneTitle: "Ana buƙatar izinin makirufo", microphoneBody: "Don duba karatunku, ku ba makirufo izini a Saituna. Har yanzu kuna iya yin atisaye ta sauraro kawai.", openSettings: "Buɗe Saituna", tryAgain: "Sake gwadawa", settingsFailed: "Ba a iya buɗe Saituna kai tsaye ba. Ku ba makirufo izini a saitunan na'urar.", listenOnlyTitle: "Atisayen sauraro kawai", listenOnlyUnavailable: "Duba karatu ba ya nan. Saurara, maimaita da ƙarfi, sannan ku kwatanta da misali.", listenOnlyAvailable: "Saurara ku maimaita da ƙarfi. Ku ba makirufo izini idan kun shirya don dubawa.", readyMicrophone: "Na shirya — gwada da makirufo", offlineTitle: "Babu haɗin intanet", offlineBody: "Duba murya yana buƙatar haɗi a yawancin na'urori. Kuna iya yin atisaye da sautin da aka sauke.", readNow: "Karanta yanzu", tapToRead: "Taɓa, sannan ka karanta da ƙarfi", listening: "Ana sauraro… Karanta yanzu.", stop: "Tsaya — na gama", checking: "Ana duba karatunku…", errorLabels: { "no-speech": "Ba a gano magana bayyananniya ba", timeout: "Lokacin sauraro ya ƙare", "not-allowed": "Ba a ba da izinin makirufo ba", network: "An kasa haɗawa da sabis ɗin murya", aborted: "An dakatar da ganewa", unknown: "Kuskuren sabis ɗin murya da ba a sani ba" } }),
  uzbek: copy({ ...english, advanced: "Kengaytirilgan", diagnosticsTitle: "Nutq diagnostikasi", diagnosticsDescription: "So‘nggi nutq tekshiruvidan batafsil ma’lumot.", recognizedText: "Aniqlangan matn", score: "Ball", language: "Til", confidence: "Ishonch", errors: "Aniqlash xatolari", noErrors: "Aniqlash xatolari yo‘q", close: "Yopish", status: "Holat", unclearTitle: "Buni aniq tushuna olmadim.", unclearBody: "Hechqisi yo‘q — bu sizga qarshi hisoblanmaydi. Qayta urinib, tabiiy gapiring.", retryTitle: "Yaxshi urinish — keling, birga yaxshilaymiz.", retryBody: "Yana tinglang va so‘zni tabiiy tarzda takrorlang. Ozgina fon shovqini muammo emas.", passedExcellent: "A’lo! Mashaalloh!", passedCorrect: "Barakalla! To‘g‘ri edi.", wordMatch: "So‘z mosligi", heard: "Eshitganim", focusSounds: "E’tibor beriladigan tovushlar", extraSounds: "Eshitilgan qo‘shimcha tovushlar", hearAgain: "Yana tinglash", microphoneTitle: "Mikrofon ruxsati kerak", microphoneBody: "O‘qishingizni tekshirish uchun Sozlamalarda mikrofonni yoqing. Faqat tinglab ham mashq qilishingiz mumkin.", openSettings: "Sozlamalarni ochish", tryAgain: "Qayta urinish", settingsFailed: "Sozlamalarni avtomatik ochib bo‘lmadi. Qurilma sozlamalarida mikrofonni yoqing.", listenOnlyTitle: "Faqat tinglab mashq", listenOnlyUnavailable: "O‘qish tekshiruvi bu yerda mavjud emas. Tinglang, baland ovozda takrorlang va namuna bilan solishtiring.", listenOnlyAvailable: "Tinglang va baland ovozda takrorlang. Tayyor bo‘lganda mikrofonni yoqing.", readyMicrophone: "Tayyorman — mikrofon bilan urinib ko‘ring", offlineTitle: "Internet aloqasi yo‘q", offlineBody: "Ko‘p qurilmalarda nutq tekshiruvi uchun aloqa kerak. Yuklangan audio bilan mashq qilishingiz mumkin.", readNow: "Hozir o‘qish", tapToRead: "Bosing va baland ovozda o‘qing", listening: "Tinglanmoqda… Hozir o‘qing.", stop: "To‘xtatish — tugatdim", checking: "O‘qishingiz tekshirilmoqda…", errorLabels: { "no-speech": "Aniq nutq aniqlanmadi", timeout: "Tinglash vaqti tugadi", "not-allowed": "Mikrofon ruxsati berilmadi", network: "Nutq xizmatiga ulanib bo‘lmadi", aborted: "Aniqlash to‘xtatildi", unknown: "Nutq xizmatining noma’lum xatosi" } }),
  kazakh: copy({ ...english, advanced: "Кеңейтілген", diagnosticsTitle: "Сөйлеу диагностикасы", diagnosticsDescription: "Соңғы сөйлеу тексерісінің толық ақпараты.", recognizedText: "Танылған мәтін", score: "Ұпай", language: "Тіл", confidence: "Сенімділік", errors: "Тану қателері", noErrors: "Тану қатесі жоқ", close: "Жабу", status: "Күйі", unclearTitle: "Мұны анық түсіне алмадым.", unclearBody: "Ештеңе етпейді — бұл сізге қарсы есептелмейді. Қайта байқап, табиғи сөйлеңіз.", retryTitle: "Жақсы әрекет — бірге жақсартайық.", retryBody: "Қайта тыңдап, сөзді табиғи түрде қайталаңыз. Аздап фондық шу кедергі емес.", passedExcellent: "Тамаша! Машаллаһ!", passedCorrect: "Жақсы! Дұрыс болды.", wordMatch: "Сөз сәйкестігі", heard: "Естігенім", focusSounds: "Назар аударатын дыбыстар", extraSounds: "Естілген артық дыбыстар", hearAgain: "Қайта тыңдау", microphoneTitle: "Микрофон рұқсаты қажет", microphoneBody: "Оқуыңызды тексеру үшін Баптауларда микрофонға рұқсат беріңіз. Тек тыңдап та жаттыға аласыз.", openSettings: "Баптауларды ашу", tryAgain: "Қайта көру", settingsFailed: "Баптауларды автоматты ашу мүмкін болмады. Құрылғы баптауларында микрофонға рұқсат беріңіз.", listenOnlyTitle: "Тек тыңдап жаттығу", listenOnlyUnavailable: "Оқу тексерісі мұнда қолжетімсіз. Тыңдап, дауыстап қайталаңыз және үлгімен салыстырыңыз.", listenOnlyAvailable: "Тыңдап, дауыстап қайталаңыз. Дайын болғанда микрофонға рұқсат беріңіз.", readyMicrophone: "Дайынмын — микрофонмен байқап көру", offlineTitle: "Интернет байланысы жоқ", offlineBody: "Көп құрылғыда сөйлеуді тексеру үшін байланыс қажет. Жүктелген аудиомен жаттыға аласыз.", readNow: "Қазір оқу", tapToRead: "Басып, дауыстап оқыңыз", listening: "Тыңдалуда… Қазір оқыңыз.", stop: "Тоқтату — бітті", checking: "Оқуыңыз тексерілуде…", errorLabels: { "no-speech": "Анық сөйлеу табылмады", timeout: "Тыңдау уақыты аяқталды", "not-allowed": "Микрофон рұқсаты берілмеді", network: "Сөйлеу қызметіне қосылу мүмкін болмады", aborted: "Тану тоқтатылды", unknown: "Сөйлеу қызметінің белгісіз қатесі" } }),
};

export function getTeacherSpeechCopy(language: TranslationLanguage): TeacherSpeechCopy {
  return TEACHER_SPEECH_COPY[language] ?? english;
}